/* chemicals_extended.js — Extended Chemical Database (~80 new compounds) */

const EXTENDED_CHEMICALS = [
  // ——— ACIDS ———
  { id:'hf', formula:'HF', name:'Acid Flohydric', shortName:'HF', type:'acid', cation:'H', anion:'F', ph:1.5, molarityRange: [0.1, 2.0], molarityPresets: ['0.1', '0.5', '1.0', '2.0'], color:'#f0fdfa', liquidColor:'rgba(167,243,208,0.6)', colorHex:'#a7f3d0', hazards:['toxic','corrosive'], badges:['acid','toxic'], molarMass:20.01, icon:'🧪', description:'Acid flohydric. CỰC KỲ NGUY HIỂM — ăn mòn xương và thủy tinh. Phải dùng bình nhựa đặc biệt.', reactions:['naoh','ca_oh_2'] },
  { id:'hbr', formula:'HBr', name:'Acid Bromhydric', shortName:'HBr', type:'acid', cation:'H', anion:'Br', ph:0.9, molarityRange: [0.1, 2.0], molarityPresets: ['0.1', '1.0', '2.0'], color:'#fef3c7', liquidColor:'rgba(254,215,170,0.5)', colorHex:'#fed7aa', hazards:['corrosive','toxic'], badges:['acid','corrosive'], molarMass:80.91, icon:'🧴', description:'Acid bromhydric. Dung dịch không màu vàng nhạt. Tính acid mạnh, ít oxy hóa hơn HCl.', reactions:['naoh','agno3'] },
  { id:'hi', formula:'HI', name:'Acid Iodhydric', shortName:'HI', type:'acid', cation:'H', anion:'I', ph:0.5, molarityRange: [0.1, 2.0], molarityPresets: ['0.1', '1.0', '2.0'], color:'#fef9c3', liquidColor:'rgba(253,224,71,0.4)', colorHex:'#fde047', hazards:['corrosive','toxic'], badges:['acid','corrosive'], molarMass:127.91, icon:'🟡', description:'Acid iodhydric. Acid mạnh nhất trong dãy HX. Dung dịch có màu vàng nhạt.', reactions:['naoh','agno3'] },
  { id:'h3po4', formula:'H₃PO₄', name:'Acid Photphoric', shortName:'H₃PO₄', type:'acid', cation:'H', anion:'PO4', ph:2.1, molarityRange: [0.1, 15.0], molarityPresets: ['0.1', '1.0', '5.0', '15.0'], color:'#f0f9ff', liquidColor:'rgba(186,230,253,0.6)', colorHex:'#bae6fd', hazards:['corrosive'], badges:['acid'], molarMass:98.0, icon:'🔬', description:'Acid photphoric. Acid ba nấc, yếu hơn H₂SO₄. Dùng trong công nghiệp phân bón và thực phẩm.', reactions:['naoh','ca_oh_2'] },
  { id:'h2s', formula:'H₂S', name:'Acid Sunfuhidric', shortName:'H₂S', type:'acid', cation:'H', anion:'S', ph:4.5, molarityRange: [0.01, 0.1], molarityPresets: ['0.01', '0.05', '0.1'], color:'#fefce8', liquidColor:'rgba(253,224,71,0.25)', colorHex:'#fef08a', hazards:['toxic','flammable'], badges:['toxic','flammable'], molarMass:34.08, icon:'💀', description:'Hydro sulfide. Khí không màu, mùi trứng thối. CỰC ĐỘC — chết người ở 700ppm. Tủ hút bắt buộc.', reactions:['naoh','agno3','cucl2'] },
  { id:'h2so3', formula:'H₂SO₃', name:'Acid Sunfurơ', shortName:'H₂SO₃', type:'acid', cation:'H', anion:'SO3', ph:2.5, molarityRange: [0.1, 0.5], molarityPresets: ['0.1', '0.3', '0.5'], color:'#f0fdf4', liquidColor:'rgba(187,247,208,0.5)', colorHex:'#bbf7d0', hazards:['corrosive'], badges:['acid'], molarMass:82.07, icon:'🧪', description:'Acid sunfurơ. Dung dịch yếu, không bền, phân hủy thành SO₂ và H₂O. Nghiên cứu thủy phân.', reactions:['naoh','ca_oh_2'] },
  { id:'hclo4', formula:'HClO₄', name:'Acid Pecloric', shortName:'HClO₄', type:'acid', cation:'H', anion:'CLO4', ph:0, molarityRange: [1.0, 12.0], molarityPresets: ['1.0', '5.0', '12.0'], color:'#f0fdfa', liquidColor:'rgba(204,251,241,0.6)', colorHex:'#ccfbf1', hazards:['corrosive','oxidizer'], badges:['acid','oxidizer'], molarMass:100.46, icon:'☢️', description:'Acid pecloric. Acid mạnh nhất trong dung dịch nước. Chất oxy hóa cực mạnh — LAB CHUYÊN MÔN.', reactions:['naoh','koh'] },
  { id:'h2c2o4', formula:'H₂C₂O₄', name:'Acid Oxalic', shortName:'H₂C₂O₄', type:'acid', cation:'H', anion:'C2O4', ph:1.3, molarityRange: [0.1, 1.0], molarityPresets: ['0.1', '0.5', '1.0'], color:'#ffffff', liquidColor:'rgba(241,245,249,0.6)', colorHex:'#f1f5f9', hazards:['toxic'], badges:['acid','toxic'], molarMass:90.03, icon:'🌿', description:'Acid oxalic (acid etanoic). Có trong cây rhubarb, me chua. Tác nhân kết tủa Ca²⁺ thành CaC₂O₄ trắng.', reactions:['naoh','ca_oh_2'] },
  { id:'h3bo3', formula:'H₃BO₃', name:'Acid Boric', shortName:'H₃BO₃', type:'acid', cation:'H', anion:'PO3', ph:5.1, molarityRange: [0.1, 0.8], molarityPresets: ['0.1', '0.3', '0.8'], color:'#ffffff', liquidColor:'rgba(248,250,252,0.4)', colorHex:'#f8fafc', hazards:[], badges:['acid'], molarMass:61.83, icon:'🅱️', description:'Acid boric. Acid rất yếu. Dùng trong thuốc sát khuẩn nhẹ và chất bảo quản thực phẩm.', reactions:['naoh'] },

  // ——— BASES ———
  { id:'koh', formula:'KOH', name:'Kali Hidroxit', shortName:'KOH', type:'base', cation:'K', anion:'OH', ph:14, form:'solid', color:'#ffffff', liquidColor:'rgba(219,234,254,0.7)', colorHex:'#dbeafe', hazards:['corrosive'], badges:['base','corrosive'], molarMass:56.11, icon:'🧊', keywords:['xut kali', 'caustic potash', 'potash'], description:'Kali hidroxit (potash). Base mạnh, tương tự NaOH. Dùng trong sản xuất xà phòng lỏng (KOH → R-COOK lỏng).', reactions:['hcl','h2so4','ch3cooh','fecl3','cucl2'] },
  { id:'ba_oh_2', formula:'Ba(OH)₂', name:'Bari Hidroxit', shortName:'Ba(OH)₂', type:'base', cation:'Ba', anion:'OH', ph:13.5, color:'#ffffff', liquidColor:'rgba(229,231,235,0.5)', colorHex:'#e5e7eb', hazards:['toxic','corrosive'], badges:['base','toxic'], molarMass:171.34, icon:'🔳', description:'Bari hidroxit. Base mạnh, tan tốt trong nước. Ion Ba²⁺ độc — không dùng trong thực phẩm.', reactions:['hcl','h2so4','na2co3'] },
  { id:'mg_oh_2', formula:'Mg(OH)₂', name:'Magie Hidroxit', shortName:'Mg(OH)₂', type:'base', cation:'Mg', anion:'OH', ph:10.4, form:'solid', color:'#ffffff', liquidColor:'rgba(241,245,249,0.5)', colorHex:'#f1f5f9', hazards:[], badges:['base'], molarMass:58.32, icon:'🥛', description:'Magie hidroxit. Ít tan trong nước (huyền phù trắng). Dùng làm thuốc kháng acid dạ dày (Milk of Magnesia).', reactions:['hcl','h2so4'] },
  { id:'al_oh_3', formula:'Al(OH)₃', name:'Nhôm Hidroxit', shortName:'Al(OH)₃', type:'base', cation:'Al', anion:'OH', ph:9, form:'solid', color:'#ffffff', liquidColor:'rgba(241,245,249,0.5)', colorHex:'#f1f5f9', hazards:[], badges:['amphoteric'], molarMass:78.0, icon:'⬜', description:'Nhôm hidroxit. HỢP CHẤT LƯỠNG TÍNH — tan trong cả acid lẫn kiềm mạnh. Dùng làm thuốc kháng acid.', reactions:['hcl','h2so4','naoh','koh'] },
  { id:'zn_oh_2', formula:'Zn(OH)₂', name:'Kẽm Hidroxit', shortName:'Zn(OH)₂', type:'base', cation:'Zn', anion:'OH', ph:9.5, form:'solid', color:'#ffffff', liquidColor:'rgba(241,245,249,0.5)', colorHex:'#f1f5f9', hazards:[], badges:['amphoteric'], molarMass:99.39, icon:'⬜', description:'Kẽm hidroxit. LƯỠNG TÍNH — tủa trắng tan trong NaOH dư (ZnO₂²⁻) and trong acid. Tan trong NH₃.', reactions:['hcl','naoh','nh3'] },
  { id:'fe_oh_2', formula:'Fe(OH)₂', name:'Sắt(II) Hidroxit', shortName:'Fe(OH)₂', type:'base', cation:'Fe2', anion:'OH', ph:9, form:'solid', color:'#84cc16', liquidColor:'rgba(132,204,22,0.5)', colorHex:'#84cc16', hazards:[], badges:['base'], molarMass:89.86, icon:'🟢', description:'Sắt(II) hidroxit. Kết tủa trắng xanh nhạt, bị oxy hóa nhanh trong không khí thành Fe(OH)₃ nâu đỏ.', reactions:['hcl','h2so4'] },
  { id:'fe_oh_3', formula:'Fe(OH)₃', name:'Sắt(III) Hidroxit', shortName:'Fe(OH)₃', type:'base', cation:'Fe3', anion:'OH', ph:9, form:'solid', color:'#92400e', liquidColor:'rgba(146,64,14,0.5)', colorHex:'#92400e', hazards:[], badges:['base'], molarMass:106.87, icon:'🟤', description:'Sắt(III) hidroxit. Kết tủa nâu đỏ đặc trưng. Sản phẩm của Fe³⁺ + OH⁻. Không tan trong nước.', reactions:['hcl','h2so4'] },
  { id:'cu_oh_2', formula:'Cu(OH)₂', name:'Đồng(II) Hidroxit', shortName:'Cu(OH)₂', type:'base', cation:'Cu2', anion:'OH', ph:9.5, form:'solid', color:'#1d4ed8', liquidColor:'rgba(29,78,216,0.4)', colorHex:'#1d4ed8', hazards:['toxic'], badges:['base','toxic'], molarMass:97.56, icon:'🔵', description:'Đồng(II) hidroxit. Tủa xanh lam đặc trưng. Bị nhiệt phân tạo CuO đen. Reagent Fehling test đường khử.', reactions:['hcl','h2so4','nh3'] },
  { id:'cr_oh_3', formula:'Cr(OH)₃', name:'Crom(III) Hidroxit', shortName:'Cr(OH)₃', type:'base', cation:'Cr3', anion:'OH', ph:9, form:'solid', color:'#15803d', liquidColor:'rgba(21,128,61,0.4)', colorHex:'#15803d', hazards:['toxic'], badges:['amphoteric','toxic'], molarMass:103.0, icon:'🟢', description:'Crom(III) hidroxit. LƯỠNG TÍNH. Tủa xanh xám, tan trong kiềm dư → CrO₂⁻ (chromite).', reactions:['hcl','naoh','koh'] },

  // ——— SALT CHLORIDES ———
  { id:'kcl', formula:'KCl', name:'Kali Clorua', shortName:'KCl', type:'salt', cation:'K', anion:'CL', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:74.55, icon:'🧂', description:'Kali clorua. Phân bón kali clorua. Chất điện giải. Muối trung tính. Nhận biết ion K⁺: ngọn lửa tím.', reactions:['agno3'] },
  { id:'bacl2', formula:'BaCl₂', name:'Bari Clorua', shortName:'BaCl₂', type:'salt', cation:'Ba', anion:'CL', ph:7, color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['toxic'], badges:['toxic'], molarMass:208.23, icon:'⬜', description:'Bari clorua. Độc with người. Thuốc thử nhận biết SO₄²⁻: tạo kết tủa trắng BaSO₄ không tan trong acid.', reactions:['h2so4','na2co3','agno3'] },
  { id:'cacl2', formula:'CaCl₂', name:'Canxi Clorua', shortName:'CaCl₂', type:'salt', cation:'Ca', anion:'CL', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:110.98, icon:'🧂', description:'Canxi clorua. Hút ẩm rất mạnh — dùng làm chất hút ẩm. Tỏa nhiệt khi hòa tan.', reactions:['agno3','na2co3'] },
  { id:'mgcl2', formula:'MgCl₂', name:'Magie Clorua', shortName:'MgCl₂', type:'salt', cation:'Mg', anion:'CL', ph:7, color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:95.21, icon:'🧂', description:'Magie clorua. Có trong nước biển. Dùng trong sản xuất đậu hủ (kết đông protein đậu nành).', reactions:['agno3','naoh'] },
  { id:'alcl3', formula:'AlCl₃', name:'Nhôm Clorua', shortName:'AlCl₃', type:'salt', cation:'Al', anion:'CL', ph:3.5, color:'#fffbeb', liquidColor:'rgba(254,243,199,0.5)', colorHex:'#fef3c7', hazards:['corrosive'], badges:['acid','corrosive'], molarMass:133.34, icon:'⬜', description:'Nhôm clorua. Muối acid do Al³⁺ thủy phân. Xúc tác Friedel-Crafts trong tổng hợp hữu cơ. Tạo khói trong không khí ẩm.', reactions:['naoh','nh3'] },
  { id:'zncl2', formula:'ZnCl₂', name:'Kẽm Clorua', shortName:'ZnCl₂', type:'salt', cation:'Zn', anion:'CL', ph:5, color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['corrosive'], badges:['corrosive'], molarMass:136.28, icon:'⬜', description:'Kẽm clorua. Muối tan, hút ẩm. Dùng trong công nghiệp hàn, nhuộm, làm giấy.', reactions:['naoh','nh3','agno3'] },
  { id:'fecl2', formula:'FeCl₂', name:'Sắt(II) Clorua', shortName:'FeCl₂', type:'salt', cation:'Fe2', anion:'CL', ph:5.5, color:'#d1fae5', liquidColor:'rgba(167,243,208,0.3)', colorHex:'#a7f3d0', hazards:[], badges:['neutral'], molarMass:126.75, icon:'🟢', description:'Sắt(II) clorua. Dung dịch xanh lục nhạt. Bị oxy hóa nhanh thành Fe³⁺. Thuốc bổ sắt.', reactions:['naoh','nh3'] },
  { id:'nh4cl', formula:'NH₄Cl', name:'Amoni Clorua', shortName:'NH₄Cl', type:'salt', cation:'NH4', anion:'CL', ph:5.5, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['acid'], molarMass:53.49, icon:'🧂', description:'Amoni clorua (muối ammoniac). Thuốc muối amoniac. Thủy phân cho môi trường acid nhẹ. Tạo khói with NaOH.', reactions:['naoh','ca_oh_2'] },
  { id:'pbcl2', formula:'PbCl₂', name:'Chì(II) Clorua', shortName:'PbCl₂', type:'salt', cation:'Pb2', anion:'CL', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(241,245,249,0.5)', colorHex:'#f1f5f9', hazards:['toxic'], badges:['toxic'], molarMass:278.1, icon:'⬛', description:'Chì(II) clorua. Muối trắng, ít tan (tan nhiều hơn trong nước nóng). Độc — kim loại nặng.', reactions:['agno3','na2co3'] },

  // ——— SALT SULFATES ———
  { id:'cuso4', formula:'CuSO₄', name:'Đồng(II) Sunfat', shortName:'CuSO₄', type:'salt', cation:'Cu2', anion:'SO4', ph:5, color:'#bfdbfe', liquidColor:'rgba(59,130,246,0.35)', colorHex:'#3b82f6', hazards:['toxic'], badges:['toxic'], molarMass:159.61, icon:'🔵', description:'Đồng(II) sunfat. Tinh thể xanh lam khi ngậm nước (CuSO₄.5H₂O). Dùng Fehling test, diệt nấm mốc.', reactions:['naoh','nh3','zn','fe'] },
  { id:'feso4', formula:'FeSO₄', name:'Sắt(II) Sunfat', shortName:'FeSO₄', type:'salt', cation:'Fe2', anion:'SO4', ph:4.5, form:'solid', color:'#d1fae5', liquidColor:'rgba(167,243,208,0.3)', colorHex:'#a7f3d0', hazards:[], badges:['neutral'], molarMass:151.91, icon:'🟢', description:'Sắt(II) sunfat. Tinh thể lục nhạt. Thuốc bổ sắt. Khử MnO₄⁻ tím thành Mn²⁺.', reactions:['naoh','nh3','kmno4'] },
  { id:'znso4', formula:'ZnSO₄', name:'Kẽm Sunfat', shortName:'ZnSO₄', type:'salt', cation:'Zn', anion:'SO4', ph:6, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:161.44, icon:'⬜', description:'Kẽm sunfat. Tinh thể trắng. Sản phẩm phản ứng Zn + H₂SO₄. Dùng trong sản xuất mực in và dệt.', reactions:['naoh','ba_oh_2'] },
  { id:'k2so4', formula:'K₂SO₄', name:'Kali Sunfat', shortName:'K₂SO₄', type:'salt', cation:'K', anion:'SO4', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:174.26, icon:'🧂', description:'Kali sunfat. Phân bón kali sunfat. Nhận biết K⁺ qua màu ngọn lửa tím và SO₄²⁻ qua BaCl₂.', reactions:['bacl2','ba_oh_2'] },
  { id:'na2so4', formula:'Na₂SO₄', name:'Natri Sunfat', shortName:'Na₂SO₄', type:'salt', cation:'Na', anion:'SO4', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:142.04, icon:'🧂', description:'Natri sunfat (muối Glauber Na₂SO₄.10H₂O). Dùng trong công nghiệp giấy, thủy tinh, nhuộm.', reactions:['bacl2','ba_oh_2'] },
  { id:'mgso4', formula:'MgSO₄', name:'Magie Sunfat', shortName:'MgSO₄', type:'salt', cation:'Mg', anion:'SO4', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:120.37, icon:'🧂', description:'Magie sunfat (muối Epsom MgSO₄.7H₂O). Dùng làm phân bón, muối tắm, thuốc nhuận tràng.', reactions:['naoh','ba_oh_2'] },
  { id:'nh4_2so4', formula:'(NH₄)₂SO₄', name:'Amoni Sunfat', shortName:'(NH₄)₂SO₄', type:'salt', cation:'NH4', anion:'SO4', ph:5.5, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['acid'], molarMass:132.14, icon:'🧂', description:'Amoni sunfat. Phân bón đạm thông dụng. Thủy phân cho môi trường acid nhẹ. Tác dụng kiềm → NH₃.', reactions:['naoh','ca_oh_2','bacl2'] },

  // ——— SALT NITRATES ———
  { id:'kno3', formula:'KNO₃', name:'Kali Nitrat', shortName:'KNO₃', type:'salt', cation:'K', anion:'NO3', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['oxidizer'], badges:['oxidizer'], molarMass:101.1, icon:'⚡', description:'Kali nitrat (diêm tiêu). Chất oxy hóa mạnh. Thành phần thuốc súng đen. Phân bón lá. Ngọn lửa tím K⁺.', reactions:['cu','zn'] },
  { id:'pb_no3_2', formula:'Pb(NO₃)₂', name:'Chì(II) Nitrat', shortName:'Pb(NO₃)₂', type:'salt', cation:'Pb', anion:'NO3', ph:6, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['toxic','oxidizer'], badges:['toxic','oxidizer'], molarMass:331.2, icon:'💀', description:'Chì(II) nitrat. Độc hại. Thuốc thử nhận biết S²⁻: giấy tẩm Pb(NO₃)₂ hóa đen trong H₂S.', reactions:['h2s','naoh','na2co3'] },
  { id:'agno3_2', formula:'AgNO₃', name:'Bạc Nitrat (dd)', shortName:'AgNO₃ 0.1M', type:'salt', cation:'Ag', anion:'NO3', ph:6, color:'#f8fafc', liquidColor:'rgba(248,250,252,0.6)', colorHex:'#f8fafc', hazards:['oxidizer','corrosive'], badges:['oxidizer'], molarMass:169.87, icon:'💊', description:'Bạc nitrat dung dịch chuẩn 0.1M. Dùng trong phân tích định tính ion halide. Tránh ánh sáng.', reactions:['hcl','nacl','kcl','hbr','hi','h2s'] },
  { id:'ca_no3_2', formula:'Ca(NO₃)₂', name:'Canxi Nitrat', shortName:'Ca(NO₃)₂', type:'salt', cation:'Ca', anion:'NO3', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['oxidizer'], badges:['oxidizer'], molarMass:164.09, icon:'⬜', description:'Canxi nitrat. Phân bón canxi-đạm. Tan rất tốt, hút ẩm mạnh. Chất oxy hóa.', reactions:['na2co3','h2so4'] },

  // ——— SALT CARBONATES/PHOSPHATES ———
  { id:'k2co3', formula:'K₂CO₃', name:'Kali Cacbonat', shortName:'K₂CO₃', type:'salt', cation:'K', anion:'CO3', ph:11.5, form:'solid', color:'#ffffff', liquidColor:'rgba(241,245,249,0.6)', colorHex:'e2e8f0', hazards:[], badges:['base'], molarMass:138.21, icon:'🧪', description:'Kali cacbonat (potash). Cho ngọn lửa tím K⁺. Base yếu, sủi bọt with acid mạnh.', reactions:['hcl','h2so4','bacl2'] },
  { id:'nahco3', formula:'NaHCO₃', name:'Natri Bicacbonat', shortName:'NaHCO₃', type:'salt', cation:'Na', anion:'HCO3', ph:8.3, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['base'], molarMass:84.01, icon:'🧂', keywords:['baking soda', 'thuoc tieu', 'bicacbonat'], description:'Natri bicacbonat (baking soda). Lưỡng tính yếu. Sủi bọt CO₂ with acid. Dùng trong thực phẩm, thuốc.', reactions:['hcl','h2so4','ch3cooh','ca_oh_2'] },
  { id:'khco3', formula:'KHCO₃', name:'Kali Bicacbonat', shortName:'KHCO₃', type:'salt', cation:'K', anion:'HCO3', ph:8.2, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['base'], molarMass:100.12, icon:'🧂', description:'Kali bicacbonat. Tương tự NaHCO₃ nhưng cung cấp kali thay natri. Sủi bọt CO₂ with acid.', reactions:['hcl','h2so4'] },
  { id:'na3po4', formula:'Na₃PO₄', name:'Natri Photphat', shortName:'Na₃PO₄', type:'salt', cation:'Na', anion:'PO4', ph:12, form:'solid', color:'#ffffff', liquidColor:'rgba(219,234,254,0.5)', colorHex:'#dbeafe', hazards:['corrosive'], badges:['base'], molarMass:163.94, icon:'🧪', description:'Natri photphat (trisodium phosphate). Base mạnh. Thuốc thử nhận biết Ag⁺ → kết tủa vàng Ag₃PO₄.', reactions:['hcl','agno3','ca_oh_2'] },
  { id:'na2s', formula:'Na₂S', name:'Natri Sulfide', shortName:'Na₂S', type:'salt', cation:'Na', anion:'S', ph:12.5, form:'solid', color:'#fffbeb', liquidColor:'rgba(254,243,199,0.5)', colorHex:'#fef3c7', hazards:['toxic','corrosive'], badges:['toxic','corrosive'], molarMass:78.04, icon:'⚠️', description:'Natri sulfide. Mùi H₂S khai hôi. Thuốc thử nhận biết kim loại nặng: CuS, PbS, ZnS... (kết tủa màu đặc trưng).', reactions:['cucl2','fecl3','bacl2','hcl'] },

  // ——— OXIDES - METAL ———
  { id:'cuo', formula:'CuO', name:'Đồng(II) Oxide', shortName:'CuO', type:'oxide', cation:'Cu2', anion:'O', form:'solid', color:'#1e293b', liquidColor:'rgba(15,23,42,0.8)', colorHex:'#1e293b', hazards:['toxic'], badges:['toxic'], molarMass:79.55, icon:'⬛', description:'Đồng(II) oxide. Bột đen. Có trong lớp oxide bề mặt đồng khi đun nóng. Tan trong acid tạo Cu²⁺ xanh.', reactions:['hcl','h2so4','h2','c2h5oh'] },
  { id:'cu2o', formula:'Cu₂O', name:'Đồng(I) Oxide', shortName:'Cu₂O', type:'oxide', cation:'Cu', anion:'O', form:'solid', color:'#b45309', liquidColor:'rgba(180,83,9,0.6)', colorHex:'#b45309', hazards:[], badges:[], molarMass:143.09, icon:'🔶', description:'Đồng(I) oxide. Bột đỏ gạch — sản phẩm Fehling test (glucose khử Cu²⁺→Cu₂O). Chỉ thị đường khử.', reactions:['hcl','h2so4'] },
  { id:'fe2o3', formula:'Fe₂O₃', name:'Sắt(III) Oxide', shortName:'Fe₂O₃', type:'oxide', cation:'Fe3', anion:'O', form:'solid', color:'#7c2d12', liquidColor:'rgba(124,45,18,0.6)', colorHex:'#7c2d12', hazards:[], badges:[], molarMass:159.69, icon:'🟫', description:'Sắt(III) oxide. Bột nâu đỏ (rỉ sét). Pigment đỏ học. Tan trong acid tạo Fe³⁺.', reactions:['hcl','h2so4'] },
  { id:'fe3o4', formula:'Fe₃O₄', name:'Sắt từ Oxide', shortName:'Fe₃O₄', type:'oxide', cation:'Fe3', anion:'O', form:'solid', color:'#0f172a', liquidColor:'rgba(15,23,42,0.8)', colorHex:'#0f172a', hazards:[], badges:[], molarMass:231.53, icon:'⬛', description:'Sắt từ oxide (magnetite). Bột đen, có từ tính. Hỗn hợp FeO + Fe₂O₃. Thuộc trường hợp số oxy hóa hỗn hợp.', reactions:['hcl','h2so4'] },
  { id:'feo', formula:'FeO', name:'Sắt(II) Oxide', shortName:'FeO', type:'oxide', cation:'Fe2', anion:'O', form:'solid', color:'#1c1917', liquidColor:'rgba(28,25,23,0.7)', colorHex:'#1c1917', hazards:[], badges:[], molarMass:71.85, icon:'⬛', description:'Sắt(II) oxide. Bột đen. Không bền trong không khí — bị oxy hóa thành Fe₂O₃. Tan trong acid.', reactions:['hcl','h2so4'] },
  { id:'al2o3', formula:'Al₂O₃', name:'Nhôm Oxide', shortName:'Al₂O₃', type:'oxide', cation:'Al', anion:'O', form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['amphoteric'], molarMass:101.96, icon:'⬜', description:'Nhôm oxide (corundum/alumina). Bột trắng cứng. LƯỠNG TÍNH: tan trong acid tạo Al³⁺, tan trong kiềm tạo AlO₂⁻.', reactions:['hcl','h2so4','naoh','koh'] },
  { id:'zno', formula:'ZnO', name:'Kẽm Oxide', shortName:'ZnO', type:'oxide', cation:'Zn', anion:'O', form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['amphoteric'], molarMass:81.39, icon:'⬜', description:'Kẽm oxide. Bột trắng. LƯỠNG TÍNH. Dùng làm kem chống nắng (SPF), thuốc mỡ. Phát quang UV-kích thích.', reactions:['hcl','h2so4','naoh','koh'] },
  { id:'mgo', formula:'MgO', name:'Magie Oxide', shortName:'MgO', type:'oxide', cation:'Mg', anion:'O', form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:[], molarMass:40.3, icon:'⬜', description:'Magie oxide (magnesia). Bột trắng. Kháng nhiệt cao. Tan trong acid, không tan trong nước lạnh.', reactions:['hcl','h2so4'] },
  { id:'cao', formula:'CaO', name:'Canxi Oxide', shortName:'CaO', type:'oxide', cation:'Ca', anion:'O', form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['corrosive'], badges:['corrosive'], molarMass:56.08, icon:'⬜', description:'Canxi oxide (vôi sống). Phản ứng mãnh liệt với nước tỏa nhiệt cao → Ca(OH)₂ (vôi tôi). Xây dựng, luyện kim.', reactions:['hcl','h2so4','h2o'] },
  { id:'na2o', formula:'Na₂O', name:'Natri Oxide', shortName:'Na₂O', type:'oxide', cation:'Na', anion:'O', form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['corrosive'], badges:['corrosive'], molarMass:61.98, icon:'⬜', description:'Natri oxide. Phản ứng mãnh liệt with nước tạo NaOH. Oxide base điển hình.', reactions:['hcl','h2so4','h2o'] },
  { id:'mno2', formula:'MnO₂', name:'Mangan(IV) Oxide', shortName:'MnO₂', type:'oxide', cation:'Mn', anion:'O', form:'solid', color:'#0f172a', liquidColor:'rgba(15,23,42,0.8)', colorHex:'#0f172a', hazards:['oxidizer'], badges:['oxidizer'], molarMass:86.94, icon:'⬛', description:'Mangan dioxide. Bột đen. Chất xúc tác nhiệt phân KClO₃ → O₂. Tăng tốc phân hủy H₂O₂. Không thay đổi sau phản ứng.', reactions:['hcl','kclo3','h2o2'] },
  { id:'kmno4', formula:'KMnO₄', name:'Kali Pemanganat', shortName:'KMnO₄', type:'salt', cation:'K', anion:'MNO4', ph:7, form:'solid', color:'#7e22ce', liquidColor:'rgba(126,34,206,0.5)', colorHex:'#7e22ce', hazards:['oxidizer','corrosive'], badges:['oxidizer'], molarMass:158.03, icon:'🟣', description:'Kali pemanganat. Tinh thể tím đen — dung dịch tím thẫm. Chất oxy hóa mạnh: MnO₄⁻ (tím) → Mn²⁺ (mất màu).', reactions:['feso4','h2s','h2c2o4','hcl'] },
  { id:'k2cr2o7', formula:'K₂Cr₂O₇', name:'Kali Dicrom', shortName:'K₂Cr₂O₇', type:'salt', cation:'K', anion:'CR2O7', ph:7, form:'solid', color:'#dc2626', liquidColor:'rgba(220,38,38,0.4)', colorHex:'#dc2626', hazards:['toxic','oxidizer','carcinogen'], badges:['toxic','oxidizer'], molarMass:294.19, icon:'🔴', description:'Kali đicromat. Tinh thể cam đỏ rực. Chất oxy hóa mạnh, GÂY UNG THƯ. Dùng hạn chế, fume hood bắt buộc.', reactions:['h2so4','feso4','h2s'] },

  // ——— OXIDES - NON-METAL ———
  { id:'so2', formula:'SO₂', name:'Lưu Huỳnh Dioxit', shortName:'SO₂', type:'gas', cation:'', anion:'SO2', color:'#fef9c3', liquidColor:'rgba(254,249,195,0.4)', colorHex:'#fef9c3', hazards:['toxic'], badges:['toxic'], molarMass:64.07, icon:'☁️', description:'Lưu huỳnh dioxide. Khí không màu, mùi hắc xộc. Acid mưa. Nhận biết: K₂Cr₂O₇ cam → xanh, Br₂ mất màu.', reactions:['naoh','ca_oh_2'] },
  { id:'so3', formula:'SO₃', name:'Lưu Huỳnh Trioxit', shortName:'SO₃', type:'gas', cation:'', anion:'SO3', color:'#fef3c7', liquidColor:'rgba(254,243,199,0.4)', colorHex:'#fef3c7', hazards:['corrosive','toxic'], badges:['corrosive','toxic'], molarMass:80.06, icon:'☁️', description:'Lưu huỳnh trioxide. Khói trắng trong không khí ẩm. Tan vào nước → H₂SO₄. Tiền chất sản xuất H₂SO₄.', reactions:['naoh','h2o'] },
  { id:'no', formula:'NO', name:'Nitơ Monoxide', shortName:'NO', type:'gas', cation:'', anion:'NO', color:'#e0f2fe', liquidColor:'rgba(224,242,254,0.3)', colorHex:'#e0f2fe', hazards:['toxic'], badges:['toxic'], molarMass:30.01, icon:'💨', description:'Nitric oxide. Không màu, gặp O₂ → nâu đỏ NO₂. Phân tử tín hiệu sinh học quan trọng trong cơ thể. Độc.', reactions:['o2'] },
  { id:'no2', formula:'NO₂', name:'Nitơ Dioxit', shortName:'NO₂', type:'gas', cation:'', anion:'NO2', color:'#fed7aa', liquidColor:'rgba(253,186,116,0.4)', colorHex:'#fb923c', hazards:['toxic'], badges:['toxic'], molarMass:46.01, icon:'🟠', description:'Nitơ dioxide. Khí nâu đỏ đặc trưng — nhận biết tức thời qua màu. CỰC ĐỘC. Gây phù phổi. Tủ hút.', reactions:['naoh','h2o'] },
  { id:'p2o5', formula:'P₂O₅', name:'Điphotpho Pentoxide', shortName:'P₂O₅', type:'oxide', cation:'', anion:'PO4', form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['corrosive'], badges:['corrosive'], molarMass:283.89, icon:'⬜', description:'Diphosphorous pentoxide. Chất hút ẩm cực mạnh. Phản ứng kịch liệt with nước → H₃PO₄. Chất sấy khô.', reactions:['h2o','naoh'] },
  { id:'sio2', formula:'SiO₂', name:'Silicon Dioxide', shortName:'SiO₂', type:'oxide', cation:'', anion:'O', form:'solid', color:'#f1f5f9', liquidColor:'rgba(241,245,249,0.6)', colorHex:'#f1f5f9', hazards:[], badges:[], molarMass:60.09, icon:'🪨', description:'Silicon dioxide (thạch anh, cát). Hợp chất bền. Là acid oxide nhưng không tan trong nước. Tan trong HF và kiềm nóng chảy.', reactions:['hf','naoh'] },

  // ——— METALS ———
  { id:'be_metal', formula:'Be', name:'Beryllium', shortName:'Be', type:'metal', cation:'Be', anion:'', form:'solid', color:'#e5e7eb', colorHex:'#d1d5db', hazards:['toxic'], badges:['toxic'], molarMass:9.01, icon:'🔘', description:'Beryllium kim loại. Kim loại đặc biệt nhẹ, bền. Cực độc! Bụi gây bệnh berylliosis phổi. Lưỡng tính: tan trong acid loãng và kiềm mạnh.', reactions:['hcl','naoh'] },
  { id:'mg', formula:'Mg', name:'Magie', shortName:'Mg', type:'metal', cation:'Mg', anion:'', form:'solid', color:'#94a3b8', colorHex:'#94a3b8', hazards:['flammable'], badges:['flammable'], molarMass:24.31, icon:'✨', description:'Magie kim loại. Kim loại nhẹ, bạc trắng. Cháy sáng rực màu trắng trong không khí. Phản ứng mạnh with acid and nước nóng.', reactions:['hcl','h2so4','h2o'] },
  { id:'al', formula:'Al', name:'Nhôm', shortName:'Al', type:'metal', cation:'Al', anion:'', form:'solid', color:'#c0c0c0', colorHex:'#9ca3af', hazards:[], badges:[], molarMass:26.98, icon:'🔩', description:'Nhôm kim loại. Kim loại phổ biến, nhẹ, bền. Phản ứng with cả acid lẫn kiềm mạnh (lưỡng tính). Ứng dụng rộng rãi.', reactions:['hcl','h2so4','naoh','koh'] },
  { id:'ca_metal', formula:'Ca', name:'Canxi (kim loại)', shortName:'Ca', type:'metal', form:'solid', color:'#d1d5db', colorHex:'#9ca3af', hazards:['flammable'], badges:['flammable'], molarMass:40.08, icon:'🔘', description:'Canxi kim loại. Phản ứng mạnh with nước tạo Ca(OH)₂ + H₂. Phản ứng with acid loãng mãnh liệt.', reactions:['hcl','h2so4','h2o'] },
  { id:'ag', formula:'Ag', name:'Bạc', shortName:'Ag', type:'metal', cation:'Ag', anion:'', form:'solid', color:'#e2e8f0', colorHex:'#94a3b8', hazards:[], badges:[], molarMass:107.87, icon:'⚪', description:'Bạc kim loại. Kim loại quý, ánh trắng. Không phản ứng HCl, H₂SO₄ loãng. Phản ứng HNO₃, H₂SO₄ đặc. Dẫn điện tốt nhất.', reactions:['hno3','h2so4'] },
  { id:'pb', formula:'Pb', name:'Chì', shortName:'Pb', type:'metal', cation:'Pb', anion:'', form:'solid', color:'#6b7280', colorHex:'#6b7280', hazards:['toxic'], badges:['toxic'], molarMass:207.2, icon:'🪙', description:'Chì kim loại. Xám, nặng, mềm. Độc — tích lũy sinh học. Phản ứng HNO₃ loãng. Bình ắc-quy acid-chì.', reactions:['hno3','h2so4'] },
  { id:'na_metal', formula:'Na', name:'Natri (kim loại)', shortName:'Na', type:'metal', cation:'Na', anion:'', form:'solid', color:'#fbbf24', colorHex:'#f59e0b', hazards:['flammable','corrosive'], badges:['flammable','corrosive'], molarMass:22.99, icon:'🔥', description:'Natri kim loại. Kim loại kiềm mềm. Phản ứng MẠNH with nước tạo NaOH + H₂ + nhiệt. Bảo quản trong dầu hỏa.', reactions:['h2o','hcl'] },
  { id:'k_metal', formula:'K', name:'Kali (kim loại)', shortName:'K', type:'metal', cation:'K', anion:'', form:'solid', color:'#fbbf24', colorHex:'#f59e0b', hazards:['flammable','corrosive'], badges:['flammable','corrosive'], molarMass:39.1, icon:'🔥', description:'Kali kim loại. Phản ứng cực mạnh with nước — có thể bốc cháy. Ngọn lửa tím đặc trưng K⁺. Bảo quản trong dầu.', reactions:['h2o','hcl'] },
  { id:'cr_metal', formula:'Cr', name:'Crom', shortName:'Cr', type:'metal', cation:'Cr', anion:'', form:'solid', color:'#64748b', colorHex:'#64748b', hazards:[], badges:[], molarMass:52.0, icon:'⚙️', description:'Crom kim loại. Cứng, bóng. Lớp oxide Cr₂O₃ bảo vệ. Thành phần thép không gỉ. Số oxy hóa +2,+3,+6.', reactions:['hcl','h2so4'] },

  // ——— NON-METALS ———
  { id:'b_solid', formula:'B', name:'Boron', shortName:'B', type:'nonmetal', cation:'', anion:'B', form:'solid', color:'#1f2937', colorHex:'#111827', hazards:['toxic'], badges:['toxic'], molarMass:10.81, icon:'🪨', description:'Boron dạng rắn. Tinh thể đen, rất cứng. Khó phản ứng ở nhiệt độ thường, khi nung nóng cháy rực với oxy.', reactions:['o2_gas'] },
  { id:'si_solid', formula:'Si', name:'Silic', shortName:'Si', type:'nonmetal', cation:'', anion:'Si', form:'solid', color:'#4b5563', colorHex:'#4b5563', hazards:[], badges:[], molarMass:28.09, icon:'⬜', description:'Silic (Silicon) bán dẫn. Chất rắn tinh thể xám đen. Không tan trong acid thường, tan trong kiềm mạnh giải phóng H₂.', reactions:['naoh','o2_gas'] },
  { id:'s', formula:'S', name:'Lưu Huỳnh', shortName:'S', type:'nonmetal', cation:'', anion:'S', form:'solid', color:'#fbbf24', colorHex:'#f59e0b', hazards:['flammable'], badges:['flammable'], molarMass:32.07, icon:'🟡', description:'Lưu huỳnh. Bột vàng. Cháy cho SO₂ mùi hắc. Tác nhân trong cao su lưu hóa, thuốc trừ nấm, thuốc súng.', reactions:['o2','naoh'] },
  { id:'p_red', formula:'P', name:'Photpho Đỏ', shortName:'P đỏ', type:'nonmetal', cation:'', anion:'P', form:'solid', color:'#dc2626', colorHex:'#dc2626', hazards:['flammable'], badges:['flammable'], molarMass:30.97, icon:'🔴', description:'Photpho đỏ (dạng bền). Bột đỏ, ít nguy hiểm hơn P trắng. Thành phần que diêm an toàn. Cần nhiệt cao mới cháy.', reactions:['o2','cl2'] },
  { id:'c_carbon', formula:'C', name:'Carbon (Than)', shortName:'C', type:'nonmetal', cation:'', anion:'C', form:'solid', color:'#0f172a', colorHex:'#0f172a', hazards:[], badges:[], molarMass:12.01, icon:'⬛', description:'Carbon (than hoạt tính / than chì). Hấp phụ mạnh. Khử oxide kim loại. Cần nhiệt cao.', reactions:['o2','fe2o3'] },
  { id:'i2', formula:'I₂', name:'Iot', shortName:'I₂', type:'nonmetal', cation:'', anion:'I', form:'solid', color:'#4c1d95', liquidColor:'rgba(76,29,149,0.4)', colorHex:'#4c1d95', hazards:['toxic'], badges:['toxic'], molarMass:253.81, icon:'🟣', description:'Iot. Tinh thể tím đen, hơi màu tím. Nhận biết tinh bột: I₂ + hồ tinh bột → xanh đen đặc trưng. Test hàm lượng tinh bột.', reactions:['na2s2o3','naoh'] },
  { id:'cl2_gas', formula:'Cl₂', name:'Khí Clo', shortName:'Cl₂', type:'gas', cation:'', anion:'CL', color:'#bbf7d0', liquidColor:'rgba(187,247,208,0.3)', colorHex:'#bbf7d0', hazards:['toxic'], badges:['toxic'], molarMass:70.9, icon:'🟢', description:'Clo khí. Màu vàng lục nhạt. Mùi hắc. Nhận biết: giấy quỳ ẩm mất màu, I₂ giải phóng từ KI. TỦ HÚT BATCH BẮT BUỘC.', reactions:['naoh','koi','h2o'] },

  // ——— SPECIAL ———
  { id:'h2o2', formula:'H₂O₂', name:'Hydro Peroxide', shortName:'H₂O₂', type:'special', ph:6.2, color:'#f0f9ff', liquidColor:'rgba(224,242,254,0.6)', colorHex:'#e0f2fe', hazards:['oxidizer'], badges:['oxidizer'], molarMass:34.01, icon:'💧', description:'Hydro peroxide 30%. Chất oxy hóa mạnh. Phân hủy → H₂O + O₂↑ khi có xúc tác MnO₂ hoặc enzym catalase. Test que tàn đốm.', reactions:['mno2','naoh'] },
  { id:'h2o2_conc', formula:'H₂O₂ (đặc)', name:'Hydro Peroxide Đặc', shortName:'H₂O₂ đặc', type:'special', ph:4.5, concentration:'90%', color:'#fff7ed', liquidColor:'rgba(255,247,237,0.85)', colorHex:'#fed7aa', hazards:['oxidizer','corrosive','explosive'], badges:['oxidizer','corrosive','danger'], molarMass:34.01, icon:'🔥', keywords:['hydrogen peroxide dac', 'oxy gia'], description:'Hydro peroxide 90%+ (đặc). NGUY CỰC KỲ NGUY HIỂM! Tiếp xúc vật liệu hữu cơ (gỗ, vải, da...) sẽ bốc cháy ngay lập tức. Đun nóng → NỔ. Được mệnh danh là "Rocket Fuel". Không để lọt tay.', reactions:['heat', 'mno2', 'catalyst'] },
  { id:'kclo3', formula:'KClO₃', name:'Kali Clorat', shortName:'KClO₃', type:'salt', cation:'K', anion:'CLO3', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['oxidizer'], badges:['oxidizer'], molarMass:122.55, icon:'⚡', keywords:['thuoc no', 'diet co'], description:'Kali clorat. Chất oxy hóa mạnh. Nhiệt phân with MnO₂ → O₂↑. NGUY HIỂM NỔ nếu lẫn lưu huỳnh hoặc than.', reactions:['mno2','h2so4'] },
  { id:'glucose', formula:'C₆H₁₂O₆', name:'Glucose', shortName:'Glucose', type:'organic', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(254,243,199,0.4)', colorHex:'#fef3c7', hazards:[], badges:[], molarMass:180.16, icon:'🍬', keywords:['duong nho', 'huyết'], description:'Glucose (đường đơn, aldose). Nhóm CHO có tính khử: Tollens → gương bạc; Fehling → Cu₂O đỏ gạch.', reactions:['agno3','cu_oh_2','naoh'] },
  { id:'sucrose', formula:'C₁₂H₂₂O₁₁', name:'Saccarose', shortName:'Saccarose', type:'organic', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(254,243,199,0.4)', colorHex:'#fef3c7', hazards:[], badges:[], molarMass:342.3, icon:'🍚', description:'Saccarose (đường mía). KHÔNG có nhóm CHO tự do → không phản ứng Tollens/Fehling. Thủy phân acid → glucose + fructose.', reactions:['hcl','h2so4'] },
  { id:'starch', formula:'(C₆H₁₀O₅)ₙ', name:'Tinh Bột', shortName:'Tinh Bột', type:'organic', form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:[], molarMass:162.14, icon:'🌾', description:'Tinh bột (polysaccharide). Không khử. Test đặc trưng: I₂ → xanh đen đậm. Thủy phân H⁺/enzym → glucose.', reactions:['i2','hcl'] },
  { id:'cellulose', formula:'(C₆H₁₀O₅)ₙ', name:'Cellulose', shortName:'Cellulose', type:'organic', form:'solid', color:'#ffffff', liquidColor:'rgba(240,253,244,0.3)', colorHex:'#f0fdf4', hazards:[], badges:[], molarMass:162.14, icon:'🧵', keywords:['cellulose', 'xenlulozo', 'soi'], description:'Cellulose. Thành phần chính của màng tế bào thực vật, bông, gỗ. Thủy phân trong H₂SO₄ đặc nóng hoặc enzym thành glucose.', reactions:['h2so4_conc'] },
  { id:'glycerol', formula:'C₃H₅(OH)₃', name:'Glycerol', shortName:'Glycerol', type:'organic', ph:7, color:'#f0fdf4', liquidColor:'rgba(240,253,244,0.7)', colorHex:'#dcfce7', hazards:[], badges:[], molarMass:92.09, icon:'🫙', description:'Glycerol (glycerin). Chất lỏng nhớt, không màu, ngọt. Sản phẩm xà phòng hóa triglyceride. Ứng dụng dược mỹ phẩm.', reactions:['hno3','naoh'] },
  { id:'ethanol', formula:'C₂H₅OH', name:'Ethanol', shortName:'C₂H₅OH', type:'organic', ph:7, color:'#f8fafc', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['flammable'], badges:['flammable'], molarMass:46.07, icon:'🍺', keywords:['con', 'ruou', 'etylic', 'roh', 'ancol', 'r' + "'oh", 'alcohol'], description:'Ethanol (rượu etylic). Dễ bay hơi, dễ cháy. Sản phẩm lên men glucose. Dung môi phổ biến. Khử CuO → Cu đỏ + acetaldehyde.', reactions:['cuo','naoh','k2cr2o7'] },
  { id:'methanol', formula:'CH₃OH', name:'Methanol', shortName:'CH₃OH', type:'organic', ph:7, color:'#f8fafc', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['toxic','flammable'], badges:['toxic','flammable'], molarMass:32.04, icon:'⚠️', description:'Methanol (rượu metylic). CỰC ĐỘC — 10mL gây mù, 30mL gây chết. Dung môi công nghiệp, không uống.', reactions:['naoh','k2cr2o7'] },
  { id:'acetaldehyde', formula:'CH₃CHO', name:'Acetaldehyde', shortName:'CH₃CHO', type:'organic', ph:7, color:'#f8fafc', liquidColor:'rgba(248,250,252,0.4)', colorHex:'#f8fafc', hazards:['flammable','toxic'], badges:['flammable','toxic'], molarMass:44.05, icon:'🧪', description:'Acetaldehyde (etanal). Nhóm CHO — có tính khử: Tollens + Fehling dương tính. Mùi táo. Sản phẩm oxy hóa ethanol.', reactions:['agno3','cu_oh_2'] },
  { id:'benzene', formula:'C₆H₆', name:'Benzen', shortName:'C₆H₆', type:'organic', ph:7, color:'#fef9c3', liquidColor:'rgba(254,249,195,0.6)', colorHex:'#fef9c3', hazards:['toxic','flammable','carcinogen'], badges:['toxic','flammable'], molarMass:78.11, icon:'⬡', description:'Benzen. Chất lỏng không màu, mùi thơm ngọt. GÂY UNG THƯ (carcinogen). Phản ứng thế ái điện tử. TỦ HÚT.', reactions:['cl2','hno3','h2so4'] },
  { id:'acetone', formula:'CH₃COCH₃', name:'Acetone', shortName:'Acetone', type:'organic', ph:7, color:'#f8fafc', liquidColor:'rgba(248,250,252,0.4)', colorHex:'#f8fafc', hazards:['flammable'], badges:['flammable'], molarMass:58.08, icon:'🧴', description:'Acetone (propanone). Dung môi hữu cơ phổ biến. Ketone — KHÔNG phản ứng Tollens (không có nhóm CHO).', reactions:['naoh'] },
  { id:'hcho', formula:'HCHO', name:'Formaldehyde', shortName:'HCHO', type:'organic', ph:7, color:'#f8fafc', liquidColor:'rgba(248,250,252,0.4)', colorHex:'#f8fafc', hazards:['toxic','flammable','carcinogen'], badges:['toxic','carcinogen'], molarMass:30.03, icon:'💀', description:'Formaldehyde (metanal). GÂY UNG THƯ. Aldehyde đơn giản nhất — Tollens/Fehling dương tính mạnh. Dung dịch 40% = formalin.', reactions:['agno3','cu_oh_2','naoh'] },
  { id:'hcooh', formula:'HCOOH', name:'Acid Formic', shortName:'HCOOH', type:'organic', ph:2.4, color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['corrosive','toxic'], badges:['acid','corrosive'], molarMass:46.03, icon:'🐜', description:'Acid formic (acid methanoic). Trong nọc kiến, ngòi ong. Acid hữu cơ mạnh nhất. Nhóm CHO → Tollens dương tính!', reactions:['naoh','agno3','cu_oh_2'] },
  { id:'ethyl_acetate', formula:'CH₃COOC₂H₅', name:'Ethyl Acetate', shortName:'CH₃COOC₂H₅', type:'organic', ph:7, color:'#f8fafc', liquidColor:'rgba(248,250,252,0.4)', colorHex:'#f8fafc', hazards:['flammable'], badges:['flammable'], molarMass:88.11, icon:'🍓', description:'Ethyl acetate (este). Mùi thơm hoa quả. Dung môi sơn, keo dán. Thủy phân acid/base → CH₃COOH + C₂H₅OH.', reactions:['naoh','hcl'] },

  // ——— HIĐROCACBON KHÔNG NO ———
  { id:'c2h2', formula:'C₂H₂', name:'Axetilen', shortName:'C₂H₂', type:'organic', ph:7, form:'gas', color:'#f0fdf4', liquidColor:'rgba(240,253,244,0.4)', colorHex:'#d1fae5', hazards:['flammable','explosive'], badges:['flammable','gas'], molarMass:26.04, icon:'🔥', keywords:['axetilen', 'acetylene', 'c2h2', 'lien ket ba'], description:'Axetilen C₂H₂. Khí không màu, mùi tỏi nhẹ, cực dễ cháy. Có liên kết ba (≡) — tham gia phản ứng cộng (H₂, HCl, H₂O, Br₂), phản ứng thế với AgNO₃/NH₃ tạo kết tủa vàng Ag₂C₂. Nhiên liệu hàn cắt kim loại (ngọn lửa 3500°C với O₂). CẢNH BÁO: Hỗn hợp C₂H₂+O₂ 60%+ sẽ NỔ mạnh!', reactions:['agno3','hcl','br2','h2o','h2','o2'] },

  { id:'c2h4', formula:'C₂H₄', name:'Etilen', shortName:'C₂H₄', type:'organic', ph:7, form:'gas', color:'#f0fdf4', liquidColor:'rgba(240,253,244,0.4)', colorHex:'#d1fae5', hazards:['flammable'], badges:['flammable','gas'], molarMass:28.05, icon:'🌿', keywords:['etilen', 'ethylene', 'c2h4', 'lien ket doi', 'chin trai'], description:'Etilen C₂H₄. Khí không màu, mùi nhẹ ngọt, dễ cháy. Liên kết đôi (=) — tham gia phản ứng cộng: Br₂ (mất màu cam), HCl → CH₃CH₂Cl, H₂O → C₂H₅OH. Hormone làm chín quả. Monome polymer polyethylene (PE).', reactions:['br2','hcl','h2o','h2','agno3'] },

  { id:'c2h6', formula:'C₂H₆', name:'Etan', shortName:'C₂H₆', type:'organic', ph:7, form:'gas', color:'#f8fafc', liquidColor:'rgba(248,250,252,0.4)', colorHex:'#f8fafc', hazards:['flammable'], badges:['flammable','gas'], molarMass:30.07, icon:'💨', keywords:['etan', 'ethane', 'c2h6'], description:'Etan C₂H₆. Khí no (hiđrocacbon bão hòa). Chỉ tham gia phản ứng thế (halogenation) với Cl₂/ánh sáng. KHÔNG làm mất màu Br₂, KHÔNG phản ứng AgNO₃/NH₃ — đây là điểm phân biệt quan trọng với C₂H₂, C₂H₄.', reactions:['cl2'] },

  // ——— NEW MASSIVE ADDITIONS ———
  { id:'hno2', formula:'HNO₂', name:'Acid Nitrơ', shortName:'HNO₂', type:'acid', cation:'H', anion:'NO2', ph:3.3, color:'#f0fdf4', liquidColor:'rgba(224,242,254,0.4)', colorHex:'#e0f2fe', hazards:['toxic'], badges:['acid'], molarMass:47.01, icon:'🧪', description:'Acid nitrơ. Tính acid yếu, không bền. Dùng để tổng hợp muối điazoni trong hữu cơ.', reactions:['naoh'] },
  { id:'hcn', formula:'HCN', name:'Acid Xyanhidric', shortName:'HCN', type:'acid', cation:'H', anion:'CN', ph:5.1, color:'#f0fdf4', liquidColor:'rgba(241,245,249,0.5)', colorHex:'#f1f5f9', hazards:['toxic','flammable'], badges:['toxic','deadly'], molarMass:27.03, icon:'💀', description:'Acid xyanhidric. KỊCH ĐỘC. Có mùi hạnh nhân đắng, gây ngạt thở ở cấp độ tế bào nhanh chóng.', reactions:['naoh'] },
  { id:'lioh', formula:'LiOH', name:'Liti Hidroxit', shortName:'LiOH', type:'base', cation:'Li', anion:'OH', ph:13.8, form:'solid', color:'#ffffff', liquidColor:'rgba(241,245,249,0.6)', colorHex:'#f1f5f9', hazards:['corrosive'], badges:['base','corrosive'], molarMass:23.95, icon:'🧊', description:'Liti hidroxit. Kiềm cực mạnh. Dùng làm chất hấp thụ CO₂ trong tàu vũ trụ và tổng hợp lithium.', reactions:['hcl','co2_gas'] },
  { id:'sr_oh_2', formula:'Sr(OH)₂', name:'Stronti Hidroxit', shortName:'Sr(OH)₂', type:'base', cation:'Sr', anion:'OH', ph:13.5, form:'solid', color:'#ffffff', liquidColor:'rgba(241,245,249,0.5)', colorHex:'#f1f5f9', hazards:['corrosive'], badges:['base','corrosive'], molarMass:121.63, icon:'🧊', description:'Stronti hidroxit. Base kiềm thổ mạnh, ít tan hơn Ba(OH)₂.', reactions:['hcl','h2so4'] },
  { id:'kbr', formula:'KBr', name:'Kali Bromua', shortName:'KBr', type:'salt', cation:'K', anion:'Br', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:119.0, icon:'🧂', description:'Kali bromua. Từng làm thuốc an thần. Dùng để tạo kết tủa AgBr vàng nhạt trong thí nghiệm vô cơ.', reactions:['agno3'] },
  { id:'nai', formula:'NaI', name:'Natri Iodua', shortName:'NaI', type:'salt', cation:'Na', anion:'I', ph:7, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:[], badges:['neutral'], molarMass:149.89, icon:'🧂', description:'Natri iodua. Phụ gia cung cấp i-ốt. Tạo kết tủa AgI vàng đậm với nước bạc.', reactions:['agno3','pb_no3_2'] },
  { id:'niso4', formula:'NiSO₄', name:'Niken(II) Sunfat', shortName:'NiSO₄', type:'salt', cation:'Ni2', anion:'SO4', ph:5.5, form:'solid', color:'#4ade80', liquidColor:'rgba(74,222,128,0.5)', colorHex:'#4ade80', hazards:['toxic'], badges:['toxic'], molarMass:154.75, icon:'🟢', description:'Niken(II) sunfat. Hợp chất chuyển tiếp có dung dịch cực kỳ xanh lục đẹp mắt. Độc và có thể gây kích ứng.', reactions:['naoh'] },
  { id:'cocl2', formula:'CoCl₂', name:'Coban(II) Clorua', shortName:'CoCl₂', type:'salt', cation:'Co2', anion:'CL', ph:6, form:'solid', color:'#f472b6', liquidColor:'rgba(244,114,182,0.5)', colorHex:'#f472b6', hazards:['toxic'], badges:['toxic'], molarMass:129.84, icon:'🌸', description:'Coban clorua. Mực tàng hình truyền thống và chỉ thị độ ẩm (xanh lam khi sấy khô, hồng nhạt khi ẩm).', reactions:['naoh','agno3'] },
  { id:'k2cro4', formula:'K₂CrO₄', name:'Kali Cromat', shortName:'K₂CrO₄', type:'salt', cation:'K', anion:'CrO4', ph:9, form:'solid', color:'#fde047', liquidColor:'rgba(253,224,71,0.6)', colorHex:'#fde047', hazards:['toxic','carcinogen'], badges:['toxic','oxidizer'], molarMass:194.19, icon:'🟡', description:'Kali cromat. Tinh thể màu vàng rực rỡ. Tạo tủa Ag₂CrO₄ đỏ gạch ngọc. Độc bảng A và gây ung thư.', reactions:['agno3','ba_oh_2'] },
  { id:'phenol', formula:'C₆H₅OH', name:'Phenol', shortName:'Phenol', type:'organic', ph:6, form:'solid', color:'#ffffff', liquidColor:'rgba(248,250,252,0.5)', colorHex:'#f8fafc', hazards:['toxic','corrosive'], badges:['toxic','acidic'], molarMass:94.11, icon:'⬡', description:'Phenol. Tinh thể độc tính rất cao, phá hủy tế bào da. Phản ứng thế cực mạnh tạo tủa trắng với dung dịch Brom.', reactions:['naoh','fecl3','br2_liquid'] },
  { id:'aniline', formula:'C₆H₅NH₂', name:'Anilin', shortName:'Anilin', type:'organic', ph:8, form:'liquid', color:'#fef3c7', liquidColor:'rgba(254,243,199,0.5)', colorHex:'#fcd34d', hazards:['toxic'], badges:['toxic'], molarMass:93.13, icon:'⬡', description:'Anilin. Chất lỏng nhờn hữu cơ. Tính base yếu. Dễ dàng tham gia thế brom tương tự như phenol.', reactions:['br2_liquid','hcl'] },
  { id:'toluene', formula:'C₆H₅CH₃', name:'Toluen', shortName:'Toluen', type:'organic', ph:7, form:'liquid', color:'#f8fafc', liquidColor:'rgba(248,250,252,0.4)', colorHex:'#f8fafc', hazards:['flammable','toxic'], badges:['flammable'], molarMass:92.14, icon:'⬡', description:'Toluen. Dung môi công nghiệp. Tan cực ít trong nước.', reactions:['kmn04'] },
  { id:'methyl_orange', formula:'MO', name:'Metyl Da Cam', shortName:'Metyl Da cam', type:'indicator', ph:7, form:'liquid', color:'#f97316', liquidColor:'rgba(249,115,22,0.6)', colorHex:'#f97316', hazards:[], badges:[], molarMass:327.33, icon:'🟠', description:'Chỉ thị metyl da cam (methyl orange). Đổi màu vàng ở môi trường kiềm và trung tính, và hóa đỏ ở pH < 3.1.', reactions:['hcl','naoh'] },
  { id:'k2s', formula:'K₂S', name:'Kali Sunfua', shortName:'K₂S', type:'salt', cation:'K', anion:'S', ph:12, form:'solid', color:'#fefce8', liquidColor:'rgba(253,224,71,0.2)', colorHex:'#fef08a', hazards:['toxic','corrosive'], badges:['salt','toxic'], molarMass:110.26, icon:'🧂', description:'Kali sunfua. Chất rắn màu vàng sẫm hoặc nâu. Sản phẩm của phản ứng cháy thuốc súng.', reactions:['hcl','agno3'] },

  // ======================================================
  // ——— PHIÊN BẢN ĐẶC / LOÃNG CỦA CÁC CHẤT PHỔ BIẾN ———
  // ======================================================

  // HCl loãng (~10%) — ít ăn mòn, không bốc khói
  { id:'hcl_dil', formula:'HCl (loãng)', name:'Acid Clohidric Loãng', shortName:'HCl loãng', type:'acid', ph:2, concentration:'10%', cation:'H', anion:'Cl', color:'#f0f9ff', liquidColor:'rgba(224,242,254,0.45)', colorHex:'#dbeafe', hazards:['corrosive'], badges:['acid'], molarMass:36.46, icon:'🧴', keywords:['hcl loang', 'acid loang'], description:'HCl loãng ~10%. Không bốc khói, ít ăn mòn hơn đặc. Tác dụng giống HCl đặc nhưng tốc độ phản ứng chậm hơn. An toàn hơn để thao tác.', reactions:['naoh','fe','zn','caco3'] },

  // H₂SO₄ loãng (~10%) — KHÔNG oxy hóa được Cu, Ag như dạng đặc
  { id:'h2so4_dil', formula:'H₂SO₄ (loãng)', name:'Acid Sunfuric Loãng', shortName:'H₂SO₄ loãng', type:'acid', ph:1, concentration:'10%', cation:'H', anion:'SO4', color:'#f8fafc', liquidColor:'rgba(241,245,249,0.7)', colorHex:'#e2e8f0', hazards:['corrosive'], badges:['acid'], molarMass:98.08, icon:'🧪', keywords:['h2so4 loang', 'sunfuric loang'], description:'H₂SO₄ loãng 10%. KHÔNG có tính oxy hóa mạnh như đặc. Không phản ứng với Cu, Ag. Zn, Fe tan → muối sunfat + H₂↑. Vẫn phải đổ acid vào nước khi pha!', reactions:['naoh','zn','fe','bacl2'] },

  // HNO₃ loãng (~10%) — tạo khí NO (không màu) thay vì NO₂ (nâu) như đặc
  { id:'hno3_dil', formula:'HNO₃ (loãng)', name:'Acid Nitric Loãng', shortName:'HNO₃ loãng', type:'acid', ph:1.5, concentration:'10%', cation:'H', anion:'NO3', color:'#fefce8', liquidColor:'rgba(254,252,232,0.6)', colorHex:'#fef9c3', hazards:['corrosive','oxidizer'], badges:['acid','oxidizer'], molarMass:63.01, icon:'🔬', keywords:['hno3 loang', 'nitric loang'], description:'HNO₃ loãng ~10%. Tác dụng với Cu tạo khí NO không màu (khác với NO₂ nâu ở đặc). Fe, Al bị thụ động trong HNO₃ đặc nhưng tan được trong loãng.', reactions:['cu','fe','naoh','zn'] },

  // NH₃ đặc (25-30%) — mùi cực khai, khói trắng khi gặp HCl
  { id:'nh3_conc', formula:'NH₃ (đặc)', name:'Amoniac Đặc', shortName:'NH₃ đặc', type:'base', ph:12, concentration:'25%', cation:'NH4', anion:'OH', color:'#f0fdf4', liquidColor:'rgba(167,243,208,0.5)', colorHex:'#bbf7d0', hazards:['toxic','corrosive'], badges:['base','toxic'], molarMass:17.03, icon:'☁️', keywords:['amoniac dac', 'nh3 dac', 'khai nong'], description:'Dung dịch NH₃ 25-30%. Mùi khai cực mạnh, gây nghẹt thở, bỏng mắt ngay lập tức. Khi gặp HCl đặc → khói trắng NH₄Cl dày đặc. BẮT BUỘC TỦ HÚT.', reactions:['hcl','h2so4','cuso4'] },

  // NaOH đặc (40-50% hoặc hạt rắn) — tỏa nhiệt cực mạnh khi hòa tan
  { id:'naoh_conc', formula:'NaOH (đặc)', name:'Natri Hidroxit Đặc', shortName:'NaOH đặc', type:'base', ph:14, concentration:'40%', cation:'Na', anion:'OH', color:'#eff6ff', liquidColor:'rgba(191,219,254,0.65)', colorHex:'#bfdbfe', hazards:['corrosive'], badges:['base','corrosive'], molarMass:40.0, icon:'🧱', keywords:['naoh dac', 'xuut xit dac', 'xut it dac'], description:'NaOH 40% hoặc hạt rắn. Ăn mòn da ngay lập tức. Tỏa nhiệt rất lớn khi hòa tan trong nước (bình nóng 80°C+). Phá hủy nhôm, silic, mô da.', reactions:['hcl','h2so4','al','si_solid'] },

  // KOH đặc (40%) — base mạnh hơn NaOH trong nhiều phản ứng hữu cơ
  { id:'koh_conc', formula:'KOH (đặc)', name:'Kali Hidroxit Đặc', shortName:'KOH đặc', type:'base', ph:14, concentration:'40%', cation:'K', anion:'OH', color:'#ecfdf5', liquidColor:'rgba(167,243,208,0.55)', colorHex:'#a7f3d0', hazards:['corrosive'], badges:['base','corrosive'], molarMass:56.11, icon:'🧱', keywords:['koh dac', 'kali hidroxit dac'], description:'KOH đặc 40%. Cực ăn mòn, phá nhôm và silic. Dùng trong phản ứng xà phòng hóa dầu mỡ, pin kiềm, tổng hợp hữu cơ.', reactions:['hcl','h2so4','al','hno3'] },

  // CH₃COOH băng / Glacial Acetic Acid (100%)
  { id:'ch3cooh_glacial', formula:'CH₃COOH (băng)', name:'Acid Axetic Băng', shortName:'Acid Axetic Băng', type:'acid', ph:1.8, concentration:'100%', cation:'H', anion:'CH3COO', color:'#fffbeb', liquidColor:'rgba(253,230,138,0.6)', colorHex:'#fde68a', hazards:['corrosive','flammable'], badges:['acid','corrosive','flammable'], molarMass:60.05, icon:'🫙', keywords:['giam bang', 'glacial', 'axetic bang', 'rcooh', 'acid cacboxylic', 'acid hữu cơ'], description:'Acid axetic băng 100% (đông đặc 16.7°C). Bốc hơi cực chua-cay hắc. Ăn mòn da, gây bỏng sâu. Dễ cháy. Phải khuấy khi pha loãng with nước vì tỏa nhiệt đáng kể.', reactions:['naoh','ethanol','na_metal'] },

  // Oleum / H₂SO₄ khói (H₂SO₄ + SO₃ hòa tan — nồng độ >100%)
  { id:'h2so4_oleum', formula:'Oleum', name:'Oleum (H₂SO₄ Khói)', shortName:'Oleum', type:'acid', ph:-1, concentration:'>100%', cation:'H', anion:'SO4', color:'#fef08a', liquidColor:'rgba(254,240,138,0.8)', colorHex:'#fde047', hazards:['corrosive','oxidizer','toxic'], badges:['acid','corrosive','oxidizer','danger'], molarMass:98.08, icon:'💀', keywords:['oleum', 'h2so4 khoi', 'sieu dac'], description:'Oleum: H₂SO₄ 98% + SO₃ hòa tan. Bốc khói trắng SO₃ liên tục trong không khí ẩm. Cực kỳ nguy hiểm, gây tử vong khi tiếp xúc. Chỉ dùng trong công nghiệp hóa chất đặc biệt với đầy đủ PPE.', reactions:['h2o','cu','naoh'] },

  // HF (Hydrofluoric Acid 48%) — acid yếu nhưng độc chết người theo cơ chế đặc biệt
  { id:'hf', formula:'HF', name:'Acid Flohydric', shortName:'HF', type:'acid', ph:3.2, concentration:'48%', cation:'H', anion:'F', color:'#f0fdf4', liquidColor:'rgba(240,253,244,0.55)', colorHex:'#dcfce7', hazards:['toxic','corrosive'], badges:['acid','corrosive','toxic','danger'], molarMass:20.01, icon:'☣️', keywords:['hf', 'acid flo', 'khac kinh'], description:'HF 48%. Acid yếu nhưng CỰC ĐỘC đặc biệt. Ion F⁻ xuyên qua da vào xương, phản ứng với Ca²⁺ gây hạ canxi máu, ngừng tim. 2% diện tích da tiếp xúc → tử vong sau vài giờ. Ăn mòn thủy tinh SiO₂. TỬ VONG DIỆN RỘNG.', reactions:['naoh'] },

  // NH₄NO₃ (Amoni Nitrat — phân đạm AN, cũng là tiền thân chất nổ)
  { id:'nh4no3', formula:'NH₄NO₃', name:'Amoni Nitrat', shortName:'NH₄NO₃', type:'salt', cation:'NH4', anion:'NO3', form:'solid', color:'#ffffff', molarMass:80.04, icon:'🧨', keywords:['nh4no3', 'amoni nitrat', 'phan dam', 'chat no'], description:'Amoni nitrat. Dùng làm phân bón (đạm 2 lá) và chất nổ công nghiệp. CỰC KỲ NGUY HIỂM khi đun nóng ở nồng độ cao hoặc không gian kín. Thủ phạm vụ nổ Beirut 2020.', reactions:['naoh','heat'] },

  // ——— NHÓM CHẤT ĐIỀU CHẾ MỚI ———
  { id:'cac2', formula:'CaC₂', name:'Canxi Cacbua', shortName:'Đất đèn', type:'salt', cation:'Ca', anion:'C2', form:'solid', color:'#4b5563', molarMass:64.1, icon:'🪨', description:'Canxi cacbua (đất đèn). Phản ứng mãnh liệt với nước tạo khí axetilen C₂H₂. Dùng trong hàn cắt và kích chín trái cây.', reactions:['h2o'] },
  { id:'ch3coona', formula:'CH₃COONa', name:'Natri Axetat', shortName:'Natri Axetat', type:'salt', cation:'Na', anion:'CH3COO', form:'solid', color:'#ffffff', molarMass:82.03, icon:'🧂', keywords:['natri axetat', 'rcoona'], description:'Natri axetat. Dùng trong phản ứng vôi tôi xút để điều chế Metan. Có tính base yếu (thủy phân).', reactions:['naoh','h2so4'] },
  { id:'nh4no2', formula:'NH₄NO₂', name:'Amoni Nitrit', shortName:'NH₄NO₂', type:'salt', cation:'NH4', anion:'NO2', form:'solid', color:'#ffffff', molarMass:64.04, icon:'🔋', description:'Amoni nitrit. Kém bền, dể bị nhiệt phân tạo khí Nitơ (N₂) và nước. Cách điều chế N₂ trong lab.', reactions:['heat'] },
  { id:'fes2', formula:'FeS₂', name:'Sắt Pirit', shortName:'Pirit sắt', type:'salt', cation:'Fe', anion:'S2', form:'solid', color:'#78350f', molarMass:119.98, icon:'💎', description:'Pyrite (Vàng găm). Đốt quặng pirit là giai đoạn đầu trong sản xuất H₂SO₄.', reactions:['o2_gas','heat'] },
  { id:'v2o5', formula:'V₂O₅', name:'Vanadi Pentoxide', shortName:'V₂O₅', type:'special', form:'solid', color:'#f59e0b', molarMass:181.88, icon:'🔶', description:'Xúc tác Vanadi pentoxide. Dùng trong quá trình tiếp xúc oxy hóa SO₂ thành SO₃.', reactions:['so2_gas'] },
  { id:'yeast', id_vn:'men', formula:'Men', name:'Men sinh học', shortName:'Men', type:'special', form:'solid', color:'#fef3c7', icon:'🍄', description:'Men rượu/Men giấm. Xúc tác sinh học cho quá trình lên men đường thành rượu hoặc rượu thành giấm.', reactions:['glucose','ethanol'] },

  // ——— KHÍ HỮU CƠ & VÔ CƠ MỚI ———
  { id:'ch4_gas', formula:'CH₄', name:'Khí Metan', shortName:'CH₄', type:'gas', form:'gas', color:'#ffffff', liquidColor:'rgba(255,255,255,0.1)', molarMass:16.04, icon:'💨', description:'Metan. Thành phần chính của khí thiên nhiên. Không màu, không mùi, cực kỳ dễ cháy.', reactions:['o2_gas'] },
  { id:'n2_gas', formula:'N₂', name:'Khí Nitơ', shortName:'N₂', type:'gas', form:'gas', color:'#ffffff', liquidColor:'rgba(255,255,255,0.05)', molarMass:28.01, icon:'🌫️', description:'Nitơ phân tử. Khí không màu, trơ ở nhiệt độ thường. Chiếm 78% bầu khí quyển.', reactions:['h2_gas'] },

  // ——— ESTER ———
  { id:'ethyl_acetate', formula:'CH₃COOC₂H₅', name:'Ethyl Acetate', shortName:'Ester', type:'special', form:'liquid', color:'#ffffff', liquidColor:'rgba(255,255,255,0.2)', colorHex:'#ffffff', hazards:['flammable'], badges:['organic', 'flammable'], molarMass:88.11, icon:'🍏', keywords:['este', 'ester', 'ethyl acetate', 'mui thom', 'rcoor' + "'", 'thủy phân'], description:'Ethyl acetate. Chất lỏng không màu, mùi thơm trái cây (táo/lên men). Nhẹ hơn nước và không tan trong nước, tạo hiện tượng phân lớp.', reactions:['naoh'] },
];


// Push all extended chemicals into the main array
document.addEventListener('DOMContentLoaded', () => {
  // Merge into global CHEMICALS
  if (typeof CHEMICALS !== 'undefined') {
    EXTENDED_CHEMICALS.forEach(c => {
      if (!CHEMICALS.find(e => e.id === c.id)) {
        // Add defaults for missing fields
        c.defaultConc = c.defaultConc || 1.0;
        c.defaultVol = c.defaultVol || 25;
        CHEMICALS.push(c);
      }
    });
    console.log(`✅ chemicals_extended.js: ${EXTENDED_CHEMICALS.length} hóa chất thêm vào. Tổng: ${CHEMICALS.length}`);
  }
});
