/* ============================================================
   phenomena_db.js — Cơ Sở Dữ Liệu Hiện Tượng Hóa Học Trực Quan
   Dành cho phòng thí nghiệm 2D — tra cứu màu sắc, kết tủa, khí
   ============================================================ */

window.PHENOMENA_DB = {

  /* ============================================================
     6.1 — BẢNG MÀU SẮC KẾT TỦA VÔ CƠ
     colorHex: màu hiển thị kết tủa trong SVG
     opacity: độ đặc của kết tủa (0.4~1.0)
     ============================================================ */
  precipitates: [
    {
      formula: 'AgCl',
      name: 'Bạc Clorua',
      colorName: 'Trắng tinh (White)',
      colorHex: '#ffffff',
      particleColor: 'rgba(255,255,255,0.98)',
      opacity: 1.0,
      icon: '⚪',
      situation: 'Kết tủa nhóm I - Phân tích định tính',
      equation: 'Ag⁺ + Cl⁻ → AgCl↓',
      note: 'Tan trong NH₃ dư tạo phức [Ag(NH₃)₂]⁺. Hóa đen ngoài ánh sáng.',
      reactants: ['agno3', 'hcl'],
      trigger: { cation: 'Ag', anion: 'Cl' },
    },
    {
      formula: 'AgBr',
      name: 'Bạc Bromua',
      colorName: 'Vàng nhạt / Màu kem (Pale yellow)',
      colorHex: '#fef3c7',
      particleColor: 'rgba(253,230,138,0.9)',
      opacity: 0.85,
      icon: '🟡',
      situation: 'Thêm AgNO₃ vào dung dịch Bromide (KBr, NaBr, HBr)',
      equation: 'Ag⁺ + Br⁻ → AgBr↓',
      note: 'Tan chậm trong NH₃ đặc. Màu vàng nhạt phân biệt với AgCl trắng và AgI vàng đậm.',
      trigger: { cation: 'Ag', anion: 'Br' },
    },
    {
      formula: 'AgI',
      name: 'Bạc Iodua',
      colorName: 'Vàng rực (Yellow)',
      colorHex: '#fde047',
      particleColor: 'rgba(253,224,71,0.95)',
      opacity: 0.92,
      icon: '🌕',
      situation: 'Thêm AgNO₃ vào dung dịch Iodide (KI, NaI, HI)',
      equation: 'Ag⁺ + I⁻ → AgI↓',
      note: 'KHÔNG tan trong NH₃. Màu vàng đậm rõ ràng — dễ nhận biết nhất trong chuỗi AgX.',
      trigger: { cation: 'Ag', anion: 'I' },
    },
    {
      formula: 'PbI₂',
      name: 'Chì(II) Iodua',
      colorName: 'Vàng sáng rực (Bright yellow)',
      colorHex: '#fbbf24',
      particleColor: 'rgba(251,191,36,0.95)',
      opacity: 0.95,
      icon: '✨',
      situation: 'Tương tác giữa Pb(NO₃)₂ và KI — thường được dùng để làm thí nghiệm "mưa vàng"',
      equation: 'Pb²⁺ + 2I⁻ → PbI₂↓',
      note: 'Golden Rain experiment. Xuất hiện như những tinh thể vàng lấp lánh khi dung dịch nguội.',
      trigger: { cation: 'Pb2', anion: 'I' },
    },
    {
      formula: 'Cu(OH)₂',
      name: 'Đồng(II) Hidroxit',
      colorName: 'Xanh lam (Blue)',
      colorHex: '#3b82f6',
      particleColor: 'rgba(29,78,216,0.75)',
      opacity: 0.75,
      icon: '🔵',
      situation: 'Nhỏ kiềm NaOH hoặc NH₃ vào dung dịch Đồng(II) (CuSO₄, CuCl₂)',
      equation: 'Cu²⁺ + 2OH⁻ → Cu(OH)₂↓',
      note: 'Tan trong NH₃ dư tạo phức xanh thẫm [Cu(NH₃)₄]²⁺. Đun nóng → CuO đen + H₂O.',
      trigger: { cation: 'Cu2', anion: 'OH' },
    },
    {
      formula: 'Fe(OH)₂',
      name: 'Sắt(II) Hidroxit',
      colorName: 'Xanh lục nhạt (Pale green)',
      colorHex: '#86efac',
      particleColor: 'rgba(134,239,172,0.7)',
      opacity: 0.7,
      icon: '🟢',
      situation: 'Nhỏ kiềm vào dung dịch Sắt(II) (FeSO₄, FeCl₂)',
      equation: 'Fe²⁺ + 2OH⁻ → Fe(OH)₂↓',
      note: 'Nhanh chóng bị oxy hóa trong không khí → Fe(OH)₃ nâu đỏ. Sự đổi màu xanh → nâu là đặc trưng của Fe²⁺.',
      trigger: { cation: 'Fe2', anion: 'OH' },
    },
    {
      formula: 'Fe(OH)₃',
      name: 'Sắt(III) Hidroxit',
      colorName: 'Đỏ nâu (Reddish-brown)',
      colorHex: '#92400e',
      particleColor: 'rgba(146,64,14,0.8)',
      opacity: 0.8,
      icon: '🟤',
      situation: 'Nhỏ kiềm vào dung dịch Sắt(III) (FeCl₃, Fe₂(SO₄)₃)',
      equation: 'Fe³⁺ + 3OH⁻ → Fe(OH)₃↓',
      note: 'Màu nâu đỏ đặc trưng, dạng keo nhớt. Thuốc thử KSCN nhạy hơn: Fe³⁺ + SCN⁻ → đỏ máu FeSCN²⁺.',
      trigger: { cation: 'Fe3', anion: 'OH' },
    },
    {
      formula: 'BaSO₄',
      name: 'Bari Sunfat',
      colorName: 'Trắng tinh (White)',
      colorHex: '#f8fafc',
      particleColor: 'rgba(255,255,255,0.9)',
      opacity: 0.9,
      icon: '⚪',
      situation: 'Dùng BaCl₂ hoặc Ba(NO₃)₂ để nhận biết gốc SO₄²⁻',
      equation: 'Ba²⁺ + SO₄²⁻ → BaSO₄↓',
      note: 'KHÔNG tan trong HCl, HNO₃ — phân biệt với các sulfate khác. Bền nhất trong các sulfate kết tủa.',
      trigger: { cation: 'Ba', anion: 'SO4' },
    },
    {
      formula: 'CaCO₃',
      name: 'Canxi Cacbonat',
      colorName: 'Trắng (White)',
      colorHex: '#f1f5f9',
      particleColor: 'rgba(241,245,249,0.85)',
      opacity: 0.85,
      icon: '🌫️',
      situation: 'Sục khí CO₂ vào nước vôi trong Ca(OH)₂; hoặc trộn muối cacbonat với muối canxi',
      equation: 'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O',
      note: 'Tan trong HCl sủi bọt CO₂ — phân biệt với BaSO₄. Sục CO₂ dư → Ca(HCO₃)₂ tan (nước lại trong).',
      trigger: { cation: 'Ca', anion: 'CO3' },
    },
    {
      formula: 'Al(OH)₃',
      name: 'Nhôm Hidroxit',
      colorName: 'Trắng keo nhớt (Gelatinous white)',
      colorHex: '#e2e8f0',
      particleColor: 'rgba(226,232,240,0.7)',
      opacity: 0.7,
      icon: '🌁',
      situation: 'Nhỏ từng lượng nhỏ NaOH vào dung dịch Al³⁺ (AlCl₃, Al₂(SO₄)₃)',
      equation: 'Al³⁺ + 3OH⁻ → Al(OH)₃↓',
      note: 'Lưỡng tính — tan trong NaOH dư → AlO₂⁻. Tan trong axit → Al³⁺. Keo nhớt đặc trưng.',
      trigger: { cation: 'Al', anion: 'OH' },
    },
    {
      formula: 'Zn(OH)₂',
      name: 'Kẽm Hidroxit',
      colorName: 'Trắng (White)',
      colorHex: '#e2e8f0',
      particleColor: 'rgba(226,232,240,0.75)',
      opacity: 0.75,
      icon: '⚪',
      situation: 'Nhỏ từng lượng nhỏ NaOH vào dung dịch Zn²⁺',
      equation: 'Zn²⁺ + 2OH⁻ → Zn(OH)₂↓',
      note: 'Lưỡng tính — tan trong NaOH dư, tan trong NH₃ dư tạo phức không màu [Zn(NH₃)₄]²⁺.',
      trigger: { cation: 'Zn', anion: 'OH' },
    },
    {
      formula: 'PbS',
      name: 'Chì(II) Sulfide',
      colorName: 'Đen (Black)',
      colorHex: '#0f172a',
      particleColor: 'rgba(15,23,42,0.95)',
      opacity: 0.95,
      icon: '⬛',
      situation: 'Thêm H₂S hoặc Na₂S vào dung dịch Pb²⁺',
      equation: 'Pb²⁺ + S²⁻ → PbS↓',
      note: 'Kết tủa đen đặc trưng, rất bền. Dùng để nhận biết ion Pb²⁺ và S²⁻.',
      trigger: { cation: 'Pb2', anion: 'S' },
    },
    {
      formula: 'Ag₂S',
      name: 'Bạc Sulfide',
      colorName: 'Đen (Black)',
      colorHex: '#1e293b',
      particleColor: 'rgba(30,41,59,0.95)',
      opacity: 0.95,
      icon: '⬛',
      situation: '2Ag⁺ + S²⁻ → Ag₂S↓ — nhận biết S²⁻',
      equation: '2Ag⁺ + S²⁻ → Ag₂S↓',
      note: 'Tại sao đồ bạc bị xỉn màu: phản ứng với H₂S ngoài không khí.',
      trigger: { cation: 'Ag', anion: 'S' },
    },
    {
      formula: 'Cr(OH)₃',
      name: 'Crom(III) Hidroxit',
      colorName: 'Xanh xám lục (Grey-green)',
      colorHex: '#166534',
      particleColor: 'rgba(22,101,52,0.7)',
      opacity: 0.7,
      icon: '🌿',
      situation: 'Nhỏ từng lượng nhỏ NaOH vào dung dịch Cr³⁺',
      equation: 'Cr³⁺ + 3OH⁻ → Cr(OH)₃↓',
      note: 'Lưỡng tính — tan trong NaOH dư → CrO₂⁻ xanh lục. Oxy hóa → CrO₄²⁻ vàng trong kiềm mạnh.',
      trigger: { cation: 'Cr3', anion: 'OH' },
    },
    {
      formula: 'Ni(OH)₂',
      name: 'Niken(II) Hidroxit',
      colorName: 'Xanh lục sáng (Bright green)',
      colorHex: '#22c55e',
      particleColor: 'rgba(34,197,94,0.7)',
      opacity: 0.7,
      icon: '💚',
      situation: 'Nhỏ NaOH vào dung dịch Ni²⁺ (NiSO₄, NiCl₂)',
      equation: 'Ni²⁺ + 2OH⁻ → Ni(OH)₂↓',
      note: 'Màu xanh lục sáng đặc trưng giúp phân biệt Ni²⁺ với Fe²⁺ (xanh lục nhạt hơn).',
      trigger: { cation: 'Ni2', anion: 'OH' },
    },
    {
      formula: 'Ag₃PO₄',
      name: 'Bạc Phosphate',
      colorName: 'Vàng (Yellow)',
      colorHex: '#d97706',
      particleColor: 'rgba(217,119,6,0.85)',
      opacity: 0.85,
      icon: '🟡',
      situation: 'Thêm AgNO₃ vào dung dịch chứa PO₄³⁻',
      equation: '3Ag⁺ + PO₄³⁻ → Ag₃PO₄↓',
      note: 'Tan trong HNO₃ loãng và NH₃. Thuốc thử (NH₄)₂MoO₄ trong HNO₃ nhạy hơn — tủa vàng canary.',
      trigger: { cation: 'Ag', anion: 'PO4' },
    },

    // ——— KẾT TỦA MỚI TỪ BÁO CÁO NGHIÊN CỨU ———
    {
      formula: 'PbI₂',
      name: 'Chì(II) Iodua — "Mưa Vàng"',
      colorName: 'Vàng rực sáng (Golden Yellow)',
      colorHex: '#fbbf24',
      particleColor: 'rgba(251,191,36,0.95)',
      opacity: 0.95,
      icon: '✨',
      situation: 'Golden Rain: Trộn Pb(NO₃)₂ và KI — kết tủa vàng rực xuất hiện khi làm nguội lại',
      equation: 'Pb²⁺ + 2I⁻ → PbI₂↓',
      note: 'Thí nghiệm "Mưa Vàng" nổi tiếng. Tinh thể vàng óng ánh. Chì RẤT ĐỘC — cần găng tay và kính bảo hộ.',
      trigger: { cation: 'Pb2', anion: 'I' },
    },
    {
      formula: 'Ag₂CrO₄',
      name: 'Bạc Chromate',
      colorName: 'Đỏ gạch / Đỏ nâu (Brick red)',
      colorHex: '#dc2626',
      particleColor: 'rgba(220,38,38,0.85)',
      opacity: 0.85,
      icon: '🔴',
      situation: 'Thêm AgNO₃ vào dung dịch chromate CrO₄²⁻',
      equation: '2Ag⁺ + CrO₄²⁻ → Ag₂CrO₄↓',
      note: 'Màu đỏ gạch đặc trưng — dùng trong chuẩn độ Mohr để nhận biết điểm tương đương khi định lượng Cl⁻.',
      trigger: { cation: 'Ag', anion: 'CrO4' },
    },
    {
      formula: 'CaF₂',
      name: 'Canxi Fluoride (Fluorite)',
      colorName: 'Trắng đục (White)',
      colorHex: '#f8fafc',
      particleColor: 'rgba(248,250,252,0.9)',
      opacity: 0.9,
      icon: '⚪',
      situation: 'Nhỏ CaCl₂ vào dung dịch fluoride (NaF, HF)',
      equation: 'Ca²⁺ + 2F⁻ → CaF₂↓',
      note: 'Khó tan nhất trong các canxi halide. Khoáng fluorspar. Dùng trong công nghiệp nhôm điện phân và thủy tinh.',
      trigger: { cation: 'Ca', anion: 'F' },
    },
    {
      formula: 'MgCO₃',
      name: 'Magie Carbonate',
      colorName: 'Trắng (White)',
      colorHex: '#f1f5f9',
      particleColor: 'rgba(241,245,249,0.85)',
      opacity: 0.85,
      icon: '🤍',
      situation: 'Trộn dung dịch muối Mg²⁺ và Na₂CO₃; hoặc MgO + CO₂',
      equation: 'Mg²⁺ + CO₃²⁻ → MgCO₃↓',
      note: 'Tan trong HCl sủi bọt CO₂. Ít tan hơn Ca(HCO₃)₂. Dùng trong thuốc kháng axit.',
      trigger: { cation: 'Mg', anion: 'CO3' },
    },
    {
      formula: 'PbCO₃',
      name: 'Chì(II) Carbonate (Bạch diên)',
      colorName: 'Trắng đục (White)',
      colorHex: '#f1f5f9',
      particleColor: 'rgba(241,245,249,0.9)',
      opacity: 0.9,
      icon: '⬜',
      situation: 'Trộn dung dịch chì(II) và carbonate',
      equation: 'Pb²⁺ + CO₃²⁻ → PbCO₃↓',
      note: 'Kết tủa trắng. Chì RẤT ĐỘC — không dùng làm sơn (đã bị cấm). Là thành phần của "bạch diên" cổ đại.',
      trigger: { cation: 'Pb2', anion: 'CO3' },
    },
  ],

  /* ============================================================
     6.2 — BẢNG MÀU SẮC DUNG DỊCH ION KIM LOẠI CHUYỂN TIẾP
     ============================================================ */
  ionColors: [
    {
      ion: 'Cu²⁺',
      symbol: 'Cu2+',
      name: 'Đồng(II)',
      colorName: 'Xanh lam (Blue)',
      colorHex: '#3b82f6',
      liquidColor: 'rgba(59,130,246,0.45)',
      icon: '🔵',
      note: 'Phức [Cu(H₂O)₄]²⁺ hấp thụ ánh sáng đỏ-cam, phát màu xanh lam. Nguồn: CuSO₄, CuCl₂.',
      relatedIds: ['cucl2', 'cuso4'],
    },
    {
      ion: 'Fe²⁺',
      symbol: 'Fe2+',
      name: 'Sắt(II)',
      colorName: 'Xanh lục nhạt (Pale green / Yellow-green)',
      colorHex: '#86efac',
      liquidColor: 'rgba(134,239,172,0.35)',
      icon: '💚',
      note: 'Màu nhạt khó thấy ở nồng độ loãng. Dễ bị oxy hóa → Fe³⁺ vàng nâu. Nguồn: FeSO₄, FeCl₂.',
      relatedIds: ['feso4'],
    },
    {
      ion: 'Fe³⁺',
      symbol: 'Fe3+',
      name: 'Sắt(III)',
      colorName: 'Vàng nâu / Đỏ cam (Yellow-brown / Orange-red)',
      colorHex: '#ea580c',
      liquidColor: 'rgba(234,88,12,0.4)',
      icon: '🟠',
      note: 'Màu thay đổi theo nồng độ và anion: FeCl₃ nâu vàng, Fe₂(SO₄)₃ vàng nhạt hơn. Nguồn: FeCl₃.',
      relatedIds: ['fecl3'],
    },
    {
      ion: 'Ni²⁺',
      symbol: 'Ni2+',
      name: 'Niken(II)',
      colorName: 'Xanh lục sáng (Bright green)',
      colorHex: '#22c55e',
      liquidColor: 'rgba(34,197,94,0.4)',
      icon: '💚',
      note: 'Màu xanh lục rực rỡ dễ nhận biết. Nguồn: NiSO₄ (nước khoáng Ni), NiCl₂.',
    },
    {
      ion: 'Co²⁺',
      symbol: 'Co2+',
      name: 'Coban(II)',
      colorName: 'Hồng / Đỏ nhạt (Pink / Red)',
      colorHex: '#f472b6',
      liquidColor: 'rgba(244,114,182,0.4)',
      icon: '🩷',
      note: 'Màu hồng duna dịch nước. CoCl₂ khan màu xanh coban (cobalt blue), hấp thụ nước → hồng. Dùng làm chỉ thị độ ẩm.',
    },
    {
      ion: 'Cr³⁺',
      symbol: 'Cr3+',
      name: 'Crom(III)',
      colorName: 'Xanh lục / Tím (Green / Violet tuỳ anion)',
      colorHex: '#16a34a',
      liquidColor: 'rgba(22,163,74,0.4)',
      icon: '🔷',
      note: 'CrCl₃ → tím xanh trong nước lạnh, xanh lục khi đun nóng. Màu phụ thuộc anion và nhiệt độ.',
    },
    {
      ion: 'MnO₄⁻',
      symbol: 'MnO4-',
      name: 'Permanganate',
      colorName: 'Tím đậm (Deep Purple)',
      colorHex: '#701a75',
      liquidColor: 'rgba(112, 26, 117, 0.7)',
      icon: '🟣',
      note: 'Hấp thụ mạnh vùng 525-545nm. Màu cực nhạy nồng độ.',
      relatedIds: ['kmno4'],
    },
    {
      ion: 'Cr₂O₇²⁻',
      symbol: 'Cr2O7 2-',
      name: 'Dichromate',
      colorName: 'Cam rực (Bright Orange)',
      colorHex: '#ea580c',
      liquidColor: 'rgba(234, 88, 12, 0.65)',
      icon: '🟠',
      note: 'Ổn định trong môi trường axit (pH < 6).',
    },
    {
      ion: 'CrO₄²⁻',
      symbol: 'CrO4 2-',
      name: 'Chromate',
      colorName: 'Vàng tươi (Golden Yellow)',
      colorHex: '#facc15',
      liquidColor: 'rgba(250, 204, 21, 0.6)',
      icon: '🟡',
      note: 'Ổn định trong môi trường kiềm (pH > 8).',
    },
    {
      ion: 'Na⁺/K⁺/Mg²⁺/Ca²⁺/Ba²⁺/Zn²⁺',
      symbol: 'Na+',
      name: 'Cation không màu',
      colorName: 'Không màu (Colorless)',
      colorHex: '#f8fafc',
      liquidColor: 'rgba(248,250,252,0.15)',
      icon: '💧',
      note: 'Các ion này không có orbital d chưa đầy — không hấp thụ ánh sáng khả kiến → dung dịch trong suốt.',
    },
  ],

  /* ============================================================
     6.3 — BẢNG HIỆN TƯỢNG SINH KHÍ
     ============================================================ */
  gasTests: [
    {
      formula: 'CO₂',
      name: 'Carbon Dioxide',
      colorName: 'Không màu, không mùi',
      colorHex: '#dbeafe',
      icon: '🌫️',
      phenomenon: 'Không màu, không duy trì sự cháy (làm tắt que đóm), làm vẩn đục nước vôi trong Ca(OH)₂.',
      tests: [
        { method: 'Que đóm cháy', result: 'Que đóm BỊ TẮT — CO₂ không duy trì sự cháy' },
        { method: 'Nước vôi trong Ca(OH)₂', result: 'Đục trắng — CaCO₃↓ kết tủa' },
        { method: 'Quỳ ẩm', result: 'Chuyển nhẹ sang ĐỎ (axit carbonic yếu)' },
      ],
      equation: 'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O',
      sources: ['HCl + CaCO₃', 'NaHCO₃ + acid', 'Lên men đường'],
      safety: 'Không độc nhưng gây ngạt khi nồng độ cao. Nặng hơn không khí.',
      bubbleColor: 'rgba(219,234,254,0.7)',
    },
    {
      formula: 'H₂',
      name: 'Hydrogen',
      colorName: 'Không màu, không mùi',
      colorHex: '#f0f9ff',
      icon: '💥',
      phenomenon: 'Không màu, mồi bằng que đóm đang cháy sẽ phát nổ lốp bốp nhỏ (popping sound).',
      tests: [
        { method: 'Que đóm đang cháy', result: '"Pop" — nổ nhỏ đặc trưng' },
        { method: 'Bong bóng xà phòng', result: 'Bay lên và nổ bùng cháy nhanh' },
      ],
      equation: 'Zn + 2HCl → ZnCl₂ + H₂↑ (hoặc 2Na + 2H₂O → 2NaOH + H₂↑)',
      sources: ['Kim loại + Axit', '2H₂O (điện phân → catot)', 'Na + H₂O'],
      safety: 'Dễ cháy nổ mạnh (H₂ + O₂ → nổ điện). Không tập trung trong không gian kín.',
      bubbleColor: 'rgba(224,242,254,0.5)',
    },
    {
      formula: 'O₂',
      name: 'Oxygen',
      colorName: 'Không màu, không mùi',
      colorHex: '#e0f2fe',
      icon: '🔥',
      phenomenon: 'Không màu, làm bùng cháy rực sáng trở lại một que tàn đốm đỏ.',
      tests: [
        { method: 'Que tàn đốm đỏ', result: 'BÙNG SÁNG TRỞ LẠI — O₂ hỗ trợ sự cháy mạnh' },
      ],
      equation: '2H₂O₂ → 2H₂O + O₂↑ (MnO₂ xúc tác)',
      sources: ['2KClO₃ —MnO₂, t°→ 2KCl + 3O₂↑', '2H₂O₂ —MnO₂→ 2H₂O + O₂↑', 'Điện phân H₂O (anot)'],
      safety: 'Không độc nhưng vật liệu dễ cháy trong O₂ đặc cháy mãnh liệt.',
      bubbleColor: 'rgba(224,242,254,0.6)',
    },
    {
      formula: 'N₂',
      name: 'Nitrogen (Nitơ)',
      colorName: 'Không màu, không mùi',
      colorHex: '#f1f5f9',
      icon: '🎈',
      phenomenon: 'Không màu, trơ về mặt hóa học ở nhiệt độ thường. Không duy trì sự cháy và sự hô hấp.',
      tests: [
        { method: 'Que đóm cháy', result: 'BỊ TẮT — N₂ không duy trì sự cháy' },
      ],
      equation: '2NaN₃ —t°→ 2Na + 3N₂↑',
      sources: ['Phân hủy natri azide (túi khí)', 'Chưng cất phân đoạn không khí lỏng'],
      safety: 'Khí trơ, nhưng nồng độ cao gây ngạt do thiếu oxy.',
      bubbleColor: 'rgba(241,245,249,0.5)',
    },
    {
      formula: 'CO',
      name: 'Carbon Monoxide',
      colorName: 'Không màu, không mùi',
      colorHex: '#64748b',
      icon: '☠️',
      phenomenon: 'CỰC ĐỘC. Không màu, không mùi, không vị nên rất khó phát hiện. Cháy với ngọn lửa xanh lam.',
      tests: [
        { method: 'Đốt trong không khí', result: 'Ngọn lửa XANH LAM đặc trưng: 2CO + O₂ → 2CO₂' },
      ],
      equation: 'SiO₂ + 3C —t° cao→ SiC + 2CO↑',
      sources: ['Đốt carbon thiếu oxy', 'SiO₂ + C (lò điện)'],
      safety: 'HẾT SỨC NGUY HIỂM. Liên kết mạnh với hemoglobin trong máu ngăn vận chuyển oxy. Có thể gây tử vong nhanh chóng.',
      bubbleColor: 'rgba(100,116,139,0.7)',
    },
    {
      formula: 'NH₃',
      name: 'Ammonia',
      colorName: 'Không màu, mùi khai nồng nặc',
      colorHex: '#d1fae5',
      icon: '🟢',
      phenomenon: 'Có mùi khai xốc (trong thực tế), làm giấy quỳ đỏ ẩm chuyển sang màu xanh.',
      tests: [
        { method: 'Quỳ đỏ ẩm', result: 'Chuyển XANH — NH₃ là bazơ' },
        { method: 'HCl khí', result: 'Tạo khói trắng NH₄Cl' },
        { method: 'Mùi', result: 'Mùi khai xốc đặc trưng — nguy hiểm!' },
      ],
      equation: 'NH₄Cl + NaOH →(t°) NaCl + NH₃↑ + H₂O',
      sources: ['NH₄⁺ + base mạnh đun nóng', 'N₂ + 3H₂ (Haber-Bosch, 500°C, Fe xúc tác)'],
      safety: 'Độc, ăn mòn đường hô hấp! Bắt buộc tủ hút và mặt nạ phải.',
      bubbleColor: 'rgba(209,250,229,0.6)',
    },
    {
      formula: 'NO₂',
      name: 'Nitrogen Dioxide',
      colorName: 'Nâu đỏ đặc trưng',
      colorHex: '#92400e',
      icon: '☠️',
      phenomenon: 'Bọt khí có màu nâu đỏ bay lên bám quanh thành miệng ống nghiệm.',
      tests: [
        { method: 'Quan sát trực tiếp', result: 'Màu NÂU ĐỎ đặc trưng — tự nhận biết' },
        { method: 'Quỳ ẩm', result: 'Chuyển đỏ — HNO₃ tạo thành' },
      ],
      equation: '4HNO₃(đặc) + Cu → Cu(NO₃)₂ + 2NO₂↑ + 2H₂O',
      sources: ['Cu + HNO₃ đặc', 'Fe + HNO₃ đặc', 'Kim loại + HNO₃ đặc'],
      safety: 'CỰC ĐỘC! Gây phù phổi, tử vong. Tuyệt đối trong tủ hút, mặt nạ phòng độc.',
      bubbleColor: 'rgba(146,64,14,0.6)',
    },
    {
      formula: 'SO₂',
      name: 'Sulfur Dioxide',
      colorName: 'Không màu, mùi hắc khét diêm sinh',
      colorHex: '#fef9c3',
      icon: '🌫️',
      phenomenon: 'Không màu, mùi hắc như diêm sinh, làm mất màu dung dịch thuốc tím (KMnO₄).',
      tests: [
        { method: 'KMnO₄ (thuốc tím)', result: 'Mất màu tím — SO₂ khử MnO₄⁻ → Mn²⁺' },
        { method: 'K₂Cr₂O₇ ẩm', result: 'Cam → Xanh lục — Cr₂O₇²⁻ bị khử → Cr³⁺' },
        { method: 'Nước Br₂', result: 'Mất màu nâu — SO₂ + Br₂ + H₂O → H₂SO₄ + HBr' },
      ],
      equation: 'Na₂SO₃ + 2HCl → 2NaCl + SO₂↑ + H₂O',
      sources: ['Sulfite + axit mạnh', 'S cháy trong O₂: S + O₂ → SO₂'],
      safety: 'Độc, kích thích đường hô hấp. Gây mưa axit. Tủ hút bắt buộc.',
      bubbleColor: 'rgba(254,249,195,0.6)',
    },
    {
      formula: 'Cl₂',
      name: 'Chlorine',
      colorName: 'Màu vàng lục nhạt',
      colorHex: '#bbf7d0',
      icon: '☠️',
      phenomenon: 'Khí màu vàng lục nhạt, làm mất màu (tẩy trắng) giấy quỳ tím ẩm.',
      tests: [
        { method: 'Quỳ tím ẩm', result: 'Đỏ rồi MẤT MÀU (bleaching) — HCl + HClO tẩy trắng' },
        { method: 'KI + hồ tinh bột', result: 'Chuyển XANH ĐEN — Cl₂ oxy hóa I⁻ → I₂' },
        { method: 'Màu khí', result: 'Vàng lục nhạt đặc trưng khi nồng độ cao' },
      ],
      equation: 'Điện phân NaCl bão hòa: 2NaCl + 2H₂O → 2NaOH + H₂↑ + Cl₂↑',
      sources: ['Điện phân NaCl', 'MnO₂ + 4HCl →(t°) MnCl₂ + Cl₂↑ + 2H₂O'],
      safety: 'CỰC ĐỘC! Vũ khí hóa học WW1. Gây hủy hoại phổi. Tủ hút và mặt nạ bắt buộc.',
      bubbleColor: 'rgba(187,247,208,0.65)',
    },
    {
      formula: 'H₂S',
      name: 'Hydrogen Sulfide',
      colorName: 'Không màu, mùi trứng thối cực mạnh',
      colorHex: '#fef9c3',
      icon: '☠️',
      phenomenon: 'Không màu, mùi trứng thối đặc trưng, tạo kết tủa đen PbS với giấy tẩm Pb(NO₃)₂.',
      tests: [
        { method: 'Giấy tẩm Pb(NO₃)₂', result: 'Đen tức thì — PbS↓ đặc trưng nhất' },
        { method: 'Mùi', result: 'Mùi trứng thối — NGUY HIỂM vì bão hòa mũi!' },
        { method: 'AgNO₃', result: 'Kết tủa đen Ag₂S' },
      ],
      equation: 'FeS + H₂SO₄ → FeSO₄ + H₂S↑',
      sources: ['Sulfide + axit', 'FeS + HCl → FeCl₂ + H₂S↑'],
      safety: 'RẤT ĐỘC! Nguy hiểm hơn H₂CN: liều 1000ppm gây chết tức thì. Tủ hút bắt buộc.',
      bubbleColor: 'rgba(253,224,71,0.4)',
    },
  ],

  /* ============================================================
     6.4 — BẢNG PHÉP THỬ MÀU NGỌN LỬA (FLAME TESTS)
     ============================================================ */
  flameTests: [
    {
      ion: 'Li⁺',
      symbol: 'Li+',
      name: 'Lithium',
      colorName: 'Đỏ tía / Đỏ thẫm (Crimson)',
      colorHex: '#dc2626',
      wavelength: '670 nm',
      icon: '🔴',
      note: 'Màu đỏ carmine rực rỡ, dễ nhận ngay. Không bị Na⁺ lấn át (khác với K⁺).',
    },
    {
      ion: 'Na⁺',
      symbol: 'Na+',
      name: 'Sodium',
      colorName: 'Vàng chói (Bright yellow / Orange-yellow)',
      colorHex: '#f59e0b',
      wavelength: '589 nm (vạch D kép)',
      icon: '🟡',
      note: 'Màu vàng RẤT MẠNH, che lấp hầu hết ion khác. Dùng kính cobalt xanh để lọc Na⁺ khi nhận biết K⁺.',
    },
    {
      ion: 'K⁺',
      symbol: 'K+',
      name: 'Potassium',
      colorName: 'Tím / Tím hoa cà (Violet / Lilac)',
      colorHex: '#7c3aed',
      wavelength: '766 nm & 404 nm',
      icon: '🟣',
      note: 'Màu tím nhạt — bị Na⁺ che khuất. PHẢI dùng kính cobalt xanh để lọc màu vàng Na trước.',
    },
    {
      ion: 'Ca²⁺',
      symbol: 'Ca2+',
      name: 'Calcium',
      colorName: 'Đỏ cam (Orange-red / Brick red)',
      colorHex: '#f97316',
      wavelength: '620 nm',
      icon: '🔶',
      note: 'Đỏ gạch ấm. Ít chói hơn Li⁺. Phân biệt: Li⁺ đỏ tươi hơn, Ca²⁺ ngả cam hơn.',
    },
    {
      ion: 'Sr²⁺',
      symbol: 'Sr2+',
      name: 'Strontium',
      colorName: 'Đỏ tươi (Bright red / Scarlet)',
      colorHex: '#ef4444',
      wavelength: '650-700 nm',
      icon: '🔴',
      note: 'Đỏ tươi nhất trong các kim loại kiềm thổ — dùng trong pháo hoa đỏ. Khác: Li đỏ tía, Sr đỏ tươi, Ca đỏ cam.',
    },
    {
      ion: 'Ba²⁺',
      symbol: 'Ba2+',
      name: 'Barium',
      colorName: 'Xanh lục ngả vàng (Yellow-green / Apple green)',
      colorHex: '#22c55e',
      wavelength: '524 nm',
      icon: '🟢',
      note: 'Màu xanh lá cây táo độc đáo. Dùng trong pháo hoa xanh. Chú ý: Ba²⁺ độc, muối hòa tan rất nguy hiểm.',
    },
    {
      ion: 'Cu²⁺',
      symbol: 'Cu2+',
      name: 'Copper',
      colorName: 'Xanh lục ngả lam (Blue-green / Verdigris)',
      colorHex: '#06b6d4',
      wavelength: '515 nm',
      icon: '💙',
      note: 'Màu xanh lơ đặc trưng — dùng trong pháo hoa xanh lam. Với HCl → ngọn lửa xanh lam đẹp hơn (CuCl₂ bay hơi).',
    },
  ],

  /* ============================================================
     6.5 — BẢNG NHẬN BIẾT NHÓM CHỨC HỮU CƠ
     ============================================================ */
  organicTests: [
    {
      group: 'Alkene / Alkyne',
      name: 'Liên kết bội (C=C, C≡C)',
      reagent: 'Nước Brom (Br₂)',
      reagentColor: 'rgba(161,60,0,0.5)',
      resultColor: 'rgba(248,250,252,0.2)',
      phenomenon: 'Dung dịch mất màu cam đỏ → không màu',
      icon: '🟤',
      equation: 'R-CH=CH-R + Br₂ → R-CHBr-CHBr-R',
      note: 'Phản ứng cộng electrophile. Nhanh ở nhiệt độ thường, không cần xúc tác. Alkyne phản ứng 2 lần.',
      colorBefore: '#b45309',
      colorAfter: 'transparent',
    },
    {
      group: 'Alkene / Alkyne',
      name: 'Liên kết bội (C=C, C≡C)',
      reagent: 'Thuốc tím KMnO₄',
      reagentColor: 'rgba(126,34,206,0.55)',
      resultColor: 'rgba(15,23,42,0.5)',
      phenomenon: 'Dung dịch mất màu tím → xuất hiện kết tủa nâu đen MnO₂',
      icon: '🟣',
      equation: 'R-CH=CH-R + KMnO₄ + H₂O → diol + MnO₂↓(nâu) + KOH',
      note: 'Oxy hóa alkene → diol (pH trung tính) hoặc cắt mạch (pH axit). MnO₂ kết tủa nâu đen đặc trưng.',
      colorBefore: '#7e22ce',
      colorAfter: '#0f172a',
    },
    {
      group: 'Alcohol (Rượu bậc 1, 2)',
      name: 'Nhóm -OH bậc 1 và 2',
      reagent: 'K₂Cr₂O₇ / H⁺ (dichromate acid)',
      reagentColor: 'rgba(234,88,12,0.5)',
      resultColor: 'rgba(22,163,74,0.5)',
      phenomenon: 'Dung dịch chuyển màu Cam → Xanh lục',
      icon: '🟠→💚',
      equation: 'R-CH₂OH + Cr₂O₇²⁻ / H⁺ → RCHO (aldehyde) + Cr³⁺(xanh)',
      note: 'Cr₂O₇²⁻ (cam) bị khử → Cr³⁺ (xanh). Rượu bậc 1 → aldehyde → axit. Rượu bậc 2 → ketone (không bị oxy hóa tiếp theo K₂Cr₂O₇). Rượu bậc 3 không bị oxy hóa.',
      colorBefore: '#ea580c',
      colorAfter: '#16a34a',
    },
    {
      group: 'Phenol',
      name: 'Nhóm Phenol (-OH gắn vòng benzene)',
      reagent: 'Dung dịch FeCl₃',
      reagentColor: 'rgba(234,88,12,0.35)',
      resultColor: 'rgba(126,34,206,0.6)',
      phenomenon: 'Xuất hiện màu tím thẫm (Violet) đặc trưng',
      icon: '🟣',
      equation: 'C₆H₅OH + FeCl₃ → phức tím [Fe(OC₆H₅)₆]³⁻',
      note: 'Phản ứng tạo phức chelate. Chỉ phenol và enol mới cho màu tím — phân biệt với alcohol thông thường. Catechol → xanh lục, resorcinol → tím xanh.',
      colorBefore: '#ea580c',
      colorAfter: '#7e22ce',
    },
    {
      group: 'Aldehyde / Glucose',
      name: 'Nhóm Aldehyde (-CHO)',
      reagent: 'Thuốc thử Tollens (AgNO₃ / NH₃)',
      reagentColor: 'rgba(248,250,252,0.3)',
      resultColor: 'rgba(226,232,240,0.9)',
      phenomenon: 'Thành ống nghiệm tráng một lớp GƯƠNG BẠC lấp lánh',
      icon: '🪞',
      equation: 'RCHO + 2[Ag(NH₃)₂]OH → RCOOˉ + 2Ag↓(gương) + 3NH₃ + H₂O',
      note: 'Phản ứng tráng bạc — Silver Mirror. Mỗi mol aldehyde → 2 mol Ag. Glucose (1 mol) → 2 mol Ag. KHÔNG đun quá mạnh: Ag₃N nguy cơ nổ!',
      colorBefore: 'transparent',
      colorAfter: '#e2e8f0',
    },
    {
      group: 'Aldehyde / Glucose',
      name: 'Nhóm Aldehyde (-CHO)',
      reagent: 'Thuốc thử Benedict / Fehling',
      reagentColor: 'rgba(29,78,216,0.4)',
      resultColor: 'rgba(180,53,9,0.7)',
      phenomenon: 'Kết tủa màu đỏ gạch (Cu₂O) xuất hiện khi đun nóng',
      icon: '🟤',
      equation: 'RCHO + 2Cu(OH)₂ + NaOH → RCOONa + Cu₂O↓(đỏ) + 3H₂O',
      note: 'Cu²⁺ (xanh) bị khử → Cu⁺ trong Cu₂O đỏ gạch. Định lượng được: đo lượng Cu₂O → tính glucose. Ketone KHÔNG phản ứng với Fehling.',
      colorBefore: '#1d4ed8',
      colorAfter: '#b45309',
    },
    {
      group: 'Carboxylic Acid',
      name: 'Nhóm Axit Carboxylic (-COOH)',
      reagent: 'Bột NaHCO₃ hoặc Na₂CO₃',
      reagentColor: 'rgba(241,245,249,0.5)',
      resultColor: 'rgba(219,234,254,0.4)',
      phenomenon: 'Sủi bọt khí dữ dội (thoát khí CO₂)',
      icon: '🫧',
      equation: 'RCOOH + NaHCO₃ → RCOONa + H₂O + CO₂↑',
      note: 'Phân biệt axit carboxylic với phenol: phenol KHÔNG sủi bọt với NaHCO₃ (axit quá yếu để đẩy HCO₃⁻). Axit carboxylic đủ mạnh để phản ứng.',
      colorBefore: 'transparent',
      colorAfter: 'rgba(219,234,254,0.4)',
    },
    {
      group: 'Primary Amine',
      name: 'Amin bậc 1 (Ar-NH₂)',
      reagent: 'HNO₂ (NaNO₂ + HCl) → muối Diazonium',
      reagentColor: 'rgba(248,250,252,0.3)',
      resultColor: 'rgba(220,38,38,0.6)',
      phenomenon: 'Hình thành thuốc nhuộm Azo có màu đỏ hoặc cam rực rỡ',
      icon: '🔴',
      equation: 'Ar-NH₂ + NaNO₂ + HCl → Ar-N≡N⁺Cl⁻ (diazonium) → Azo dye (đỏ/cam)',
      note: 'Phản ứng diazotization (0-5°C). Diazonium coupling với naphthol/phenol → thuốc nhuộm Azo màu rực rỡ. Amin bậc 2, 3 không cho phản ứng này.',
      colorBefore: 'transparent',
      colorAfter: '#dc2626',
    },
    {
      group: 'Ester / Lipid',
      name: 'Nhóm Ester (-COO-)',
      reagent: 'NaOH (đun nóng) — Xà phòng hóa',
      reagentColor: 'rgba(239,246,255,0.5)',
      resultColor: 'rgba(248,250,252,0.6)',
      phenomenon: 'Hỗn hợp trở nên nhớt và tạo bọt xà phòng',
      icon: '🧼',
      equation: 'RCOOR\' + NaOH → RCOONa (xà phòng) + R\'OH',
      note: 'NaOH → xà phòng rắn (bánh). KOH → xà phòng lỏng. Glycerol là sản phẩm phụ — dùng trong mỹ phẩm.',
      colorBefore: 'transparent',
      colorAfter: 'rgba(248,250,252,0.6)',
    },
    {
      group: 'Protein / Amino Acid',
      name: 'α-Amino Acid, Protein',
      reagent: 'Ninhydrin (đun nhẹ)',
      reagentColor: 'rgba(248,250,252,0.2)',
      resultColor: 'rgba(109,40,217,0.6)',
      phenomenon: 'Phức màu tím Ruhemann — tất cả amino acid (trừ Proline → vàng)',
      icon: '🟣',
      equation: 'Amino acid + Ninhydrin → Ruhemann purple (tím)',
      note: 'Phản ứng ninhydrin nhạy cực cao — phát hiện lượng vết amino acid. Proline (cyclic) → vàng thay tím. Dùng trong sắc ký giấy để hiện band protein.',
      colorBefore: 'transparent',
      colorAfter: '#6d28d9',
    },
  ],

  /* ============================================================
     METHODS: Tra cứu nhanh theo cation/anion
     ============================================================ */

  /** Lấy màu kết tủa khi mix cation + anion */
  getPrecipitateColor(cationId, anionId) {
    const c = cationId?.replace(/\d/g, '').toUpperCase();
    const a = anionId?.toUpperCase();
    const match = this.precipitates.find(p =>
      p.trigger &&
      p.trigger.cation.toUpperCase() === c &&
      p.trigger.anion.toUpperCase() === a
    );
    return match ? { color: match.particleColor, hex: match.colorHex, formula: match.formula, name: match.colorName } : null;
  },

  /** Lấy màu dung dịch ion */
  getIonSolutionColor(ionSymbol) {
    const match = this.ionColors.find(i =>
      i.symbol.toLowerCase().includes(ionSymbol.toLowerCase())
    );
    return match ? match.liquidColor : null;
  },

  /** Tra cứu màu ion từ hóa chất trong CHEMICALS db */
  getLiquidColorForChem(chemId) {
    // Map chemId → ion để tra màu chuẩn
    const MAP = {
      cucl2: 'Cu2+', cuso4: 'Cu2+',
      fecl3: 'Fe3+',
      feso4: 'Fe2+', fecl2: 'Fe2+',
      kmno4: 'MnO4-',
      k2cr2o7: 'Cr2O7 2-', k2cro4: 'CrO4 2-',
      nicl2: 'Ni2+', niso4: 'Ni2+',
      cocl2: 'Co2+', coso4: 'Co2+',
      mn_metal: 'Mn2+', cr_metal: 'Cr3+',
      mncl2: 'Mn2+', crcl3: 'Cr3+',
    };
    const ion = MAP[chemId.toLowerCase()];
    if (!ion) return null;
    return this.getIonSolutionColor(ion);
  },

  /** Tra cứu hiệu ứng cháy dựa trên nhiên liệu */
  getCombustionEffect(fuelId) {
    const EFFECTS = {
      's_solid': { effect: 'bubbles-intense', color: 'rgba(59, 130, 246, 0.5)', msg: '🔥 Lưu huỳnh cháy với ngọn lửa màu xanh lam nhạt.' },
      'p_red': { effect: 'precipitate-white-cloud', color: 'rgba(255, 255, 255, 0.8)', msg: '🌫️ Photpho cháy tạo ra khói trắng P₂O₅ dày đặc.' },
      'mg_metal': { effect: 'bubbles-violent', color: 'rgba(255, 255, 255, 0.95)', msg: '✨ Magie cháy sáng rực rỡ với ánh sáng trắng chói.' },
      'na_metal': { effect: 'bubbles-intense', color: 'rgba(245, 158, 11, 0.8)', msg: '🔥 Natri cháy với ngọn lửa màu vàng chói.' },
      'k_metal': { effect: 'bubbles-intense', color: 'rgba(167, 139, 250, 0.8)', msg: '🔥 Kali cháy với ngọn lửa màu tím.' },
      'h2_gas': { effect: 'bubbles-violent', color: 'rgba(224, 242, 254, 0.6)', msg: '💥 Hydro cháy nổ mạnh tạo ra nước.' }
    };
    return EFFECTS[fuelId] || { effect: 'bubbles-intense', color: '#f59e0b', msg: '🔥 Chất đang cháy mãnh liệt.' };
  },


  /* ============================================================ 
     6.6 — BẢNG PHẢN ỨNG HÒA TAN (DISSOLUTION)
     Xác định các chất có khả năng làm tan kết tủa đã hình thành
     ============================================================ */
  dissolutions: [
    {
      precipitates: ['AgCl', 'AgBr'],
      reagent: 'NH3',
      observation: 'Kết tủa tan trong dung dịch Amoniac tạo phức tan [Ag(NH₃)₂]⁺.',
      equation: 'AgX + 2NH₃ → [Ag(NH₃)2]X',
      clearPrecipitate: true,
      effect: 'bubbles-fast'
    },
    {
      precipitates: ['CaCO3', 'BaCO3', 'MgCO3', 'BaSO3', 'CaSO3'],
      reagent: 'acid',
      observation: 'Kết tủa tan sủi bọt mạnh khí không màu ($CO_2$ hoặc $SO_2$).',
      equation: 'Muối không tan + Acid → Muối tan + Khí↑ + H₂O',
      clearPrecipitate: true,
      effect: 'bubbles-intense'
    },
    {
      precipitates: ['Cu(OH)2', 'Fe(OH)2', 'Fe(OH)3', 'Mg(OH)2', 'Al(OH)3', 'Zn(OH)2'],
      reagent: 'acid',
      observation: 'Kết tủa tan dần trong dung dịch axit.',
      equation: 'Hydroxide + Acid → Muối tan + H₂O',
      clearPrecipitate: true,
      effect: 'bubbles-fast'
    },
    {
      precipitates: ['Al(OH)3', 'Zn(OH)2', 'Pb(OH)2', 'Cr(OH)3'],
      reagent: 'base',
      observation: 'Kết tủa lưỡng tính tan trong kiềm dư ($NaOH$).',
      equation: 'Hydroxide lưỡng tính + OH⁻ → Aluminate/Zincate tan',
      clearPrecipitate: true,
      effect: 'bubbles-fast'
    },
    {
      precipitates: ['Cu(OH)2', 'Zn(OH)2', 'Ni(OH)2', 'Ag2O'],
      reagent: 'NH3',
      observation: 'Kết tủa tan trong NH₃ dư tạo phức amin tan màu đặc trưng.',
      equation: 'Hydroxide + NH₃ → Phức tan',
      clearPrecipitate: true,
      effect: 'bubbles-fast'
    }
  ]

};

console.log('🎨 Phenomena DB loaded:', {
  precipitates: window.PHENOMENA_DB.precipitates.length,
  ionColors: window.PHENOMENA_DB.ionColors.length,
  gasTests: window.PHENOMENA_DB.gasTests.length,
  flameTests: window.PHENOMENA_DB.flameTests.length,
  organicTests: window.PHENOMENA_DB.organicTests.length,
});
